### ISSUE TITLE
Using RPC console window on Mac

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#1023]
Note: This is not a new issue. The bug existed since 6-12 months ago. Hence it's not related to #954 

When I try to type, it plays the Mac sound "You can't do that!"

https://www.dropbox.com/s/kz3rijd6i4dm50b/ScreenFlow234.mp4?dl=0

**Comment by sickpig** [comment]
@DesWurstes 

just compiled current `dev` branch and I was not able to reproduce the problem. This a screenshot showing that submitting RPC calls from debug windows is working.

![rpc-qt](https://user-images.githubusercontent.com/1469203/40916779-4f7f408e-6801-11e8-9cef-d54854bafaae.png)

I'm going to try using the released 1.3.0.1 binaries and report back.

**Comment by DesWurstes** [comment]
When I try downloading the older versions, it also doesn't happen, due to choosing an empty datadir. I guess it might happen if you complete testnet syncing and run it.

**Comment by sickpig** [comment]
ok will try syncing the testnet.

**Comment by sickpig** [comment]
@DesWurstes tried to reproduce the problem on a fully synced `testnet`, no luck w/ current `dev`.

Trying to reproduce it with 1.3.0.1 released gitian binaries.

**Comment by sickpig** [comment]
@DesWurstes no luck no issue even w/ the released binaries. I found a small GUI inconvenience using BU 1.3.0.1 cash binaries: basically the application menu is not accessible until you access the apple main menu first (this could be due to the fact that locally built binaries used a newer version of Qt, 5.11 vs 5.6).

**Comment by DesWurstes** [comment]
Somehow it's very difficult to reproduce, I'm going to close this issue until I am able to reproduce this in a VM.
