### ISSUE TITLE
blocknotify not working in v1.2.0.1

### ISSUE THREAD

**Issue by jmanini** [gandrewstone/bitcoin#1035]
I'm running bitcoind with the following options:

blocknotify=/opt/bitcoin/data/sendNewBlock.sh %s
walletnotify=/opt/bitcoin/data/sendNewTx.sh %s

both scripts are basically the same and invoke curl to pass the hash argument to other service.

walletnotify works perfectly while blocknotify doesn't

**Comment by sickpig** [comment]
thanks for the heads up! looking into it.

**Comment by sickpig** [comment]
@jmanini you could try if #1037 is working for you

**Comment by jmanini** [comment]
Problem solved in v1.3.0.0. Thank you!
