### ISSUE TITLE
-uacomment CLI/config parameter no longer works as expected

### ISSUE THREAD

**Issue by Justaphf** [gandrewstone/bitcoin#1061]
The `uacomment` CLI and config file parameter no longer works as expected.

The argument is still accepted as a valid option, and the value is parsed and validated, however it is no longer included in the sub-version string presented to peers.  This is a result of the `BUComments` vector taking the place of the `uacomments` vector in all but one location in the code.

Current behavior:
- `uacomment` argument is still parsed in and validated, though the sub-version max length check is performed with no knowledge of the `BUCommetns` vector
- `uacomment` is added to the sub-version displayed on the `Debug Window`'s `Information` tab for the `User Agent` field, and never used anywhere else
- sub-version string sent to peers only contains the computed EB and AD values contained in `BUComments`, the `uacomment` is ignored

Depending on what is intended here, either the `uacomment` argument should be marked as deprecated and a warning given to the user in the log file that the parameter is being ignored, or functionality related to the user agent string should be updated to include the comment after the EB and AD parameters.

If the former option is desired then:
- add a warning message about the parameter being deprecated when detected as a CLI argument or config file parameter
- remove parsing and validation of the parameter in `init.cpp`
- compute the sub-version displayed in the `Debug Window`'s `Information` tab for the `User Agent` field to show the EB and AD settings, same as the sub-version sent to peers.  Currently this sub-version string is computed in `init.cpp` based on the `uacomment`, not EB/AD, and never changed
- if the EB and/or AD value is changed at runtime, the value displayed on in the `Debug Window` also needs to be recomputed

If the latter option is desired, then:
- the validation for the sub-version string length needs to be updated to take into account EB and AD parameters consuming the first positions, thus shortening the allowable length for the user agent comment.
- the length check needs to be re-verified if the user modifies the EB and/or AD value at runtime.
  - this also means a potential change in behavior, as the current validation errors and quits if the total sub-version length with the `uacomment` added is longer than the allowable limit.  For changes to EB or AD at runtime which may affect the `BUComments` length, a previously valid `uacomment` may become invalid.  This would need to be handled either by truncating the `uacomment` such that the length is not exceeded, or the change to the EB or AD would need to be prevented as a validation error.  Truncation is the simplest option, but contrary to prior behavior.
- add unit tests to verify formatting of sub-version string with and without the optional `aucomment` parameter, but always taking into account the `BUComments` vector for EB and AD
  - be aware of the unit tests in `excessiveblock_test.cpp` related to EB/AD and the `BUComments` vector as this verifies proper formatting of EB/AD parameters.

**Comment by sickpig** [comment]
I think that the right thing to do will be to have the `uacomment` reinstated.

IMHO in case that the subver string becomes too long we should truncate the it, preserving EB/AD info, to make it fit and raise a warning in the log.

Same applies to the case when a user changes EB/AD at run-time so that subver become too long.

**Comment by sickpig** [comment]
@Justaphf #1830 should fix this issue

**Comment by Justaphf** [comment]
Fixed by #1830, closing
