### ISSUE TITLE
"Freeze Available" in logs after upgrading to 1.3.0.1

### ISSUE THREAD

**Issue by Affinity121** [gandrewstone/bitcoin#1090]
> 2018-05-17 12:33:46 init message: Done loading
> 2018-05-17 12:33:52 ERROR: AcceptBlockHeader: block 0000000000000000011ada8bd08f46074f44a8f155396f43e38acf9501c49103 height 530359 is marked invalid
> 2018-05-17 12:33:53 ERROR: AcceptBlockHeader: block 0000000000000000011ada8bd08f46074f44a8f155396f43e38acf9501c49103 height 530359 is marked invalid
> 2018-05-17 12:33:57 P2P peers available. Skipped DNS seeding.
> 2018-05-17 12:33:57 Bitnodes API seeding temporarily disabled
> 2018-05-17 12:33:57 dnsseed thread exit
> 2018-05-17 12:34:03 ERROR: AcceptBlockHeader: block 0000000000000000011ada8bd08f46074f44a8f155396f43e38acf9501c49103 height 530359 is marked invalid
> 2018-05-17 12:36:52 Freeze Available CTxOut(nValue=0.05000000, scriptPubKey=76a914f4a10739f0fb83c6ed3a1efa) MINE=4
>  Freeze Available CTxOut(nValue=0.24097054, scriptPubKey=76a9143a8ff38d54ba371553c0b97c) MINE=0
>  Freeze Available CTxOut(nValue=0.07590000, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=0.32190000, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=0.05982400, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=0.00396113, scriptPubKey=76a91472dd33ffb50b0c4846b77067) MINE=4
>  Freeze Available CTxOut(nValue=0.04389300, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=1.99989300, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=0.00213939, scriptPubKey=76a91432419e475c9fa4593bd041ae) MINE=4
>  Freeze Available CTxOut(nValue=0.01165265, scriptPubKey=76a914879ab5d0e33b4f553bbeba42) MINE=0
>  Freeze Available CTxOut(nValue=0.16500000, scriptPubKey=76a91428d8f0d1cadea529b167fc50) MINE=4
>  Freeze Available CTxOut(nValue=0.41200556, scriptPubKey=76a914dac832e8e675c1a7d79eb88c) MINE=0
>  Freeze Available CTxOut(nValue=0.06680000, scriptPubKey=76a914d2a12f1d3524e04a82a093c4) MINE=0
>  Freeze Available CTxOut(nValue=0.10000000, scriptPubKey=76a914a0156edb240db5ffa4cd7648) MINE=4

**Comment by Affinity121** [comment]
I installed newest version of Bitcoin Unlimited Cash Edition, and my wallet stopped to synchronize. 8 connections, but 'No block source available...' message in the status bar. What is wrong with it?

**Comment by sickpig** [comment]
Did you upgrade after the fork happened?

@Affinity121 if this is the case, try to invalidate a pre fork block. Once the client rolled back to that block - 1 (look at the debug.log) try to reconsider the same block.

E.g. from the debug window:
```
invalidateblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e
```
And then
```
reconsiderblock 000000000000000000434c281fb3ed692efea5af769aedb090b2b9f395b5386e
```

**Comment by Affinity121** [comment]
Okay, it started to work correctly. Thank you.

**Comment by sickpig** [comment]
Ok great. Closing.
