### ISSUE TITLE
There is no accessible build instruction

### ISSUE THREAD

**Issue by deadalnix** [gandrewstone/bitcoin#118]
Here: https://github.com/BitcoinUnlimited/BitcoinUnlimited

There needs to be build instruction or a big fat link toward build instructions. The public one addresses on github is developer and developer cannot develop with first getting things to build.

**Comment by sickpig** [comment]
@deadalnix we just add such instructions to the README.md and add more detailed one in `doc/quick-install.md`

please let me know if you though it's enough.

**Comment by sickpig** [comment]
@deadalnix did you review the documentation? could we close/update the status of this issue?

**Comment by deadalnix** [comment]
Yesyou can close.

**Comment by sickpig** [comment]
Cool, but I can't close. I'm not a admin of this repo. So it's up to the owner (you)or @gandrewstone.
