### ISSUE TITLE
getminingcandidate: add configurable space for the coinbase transaction

### ISSUE THREAD

**Issue by gandrewstone** [gandrewstone/bitcoin#1238]
See: https://github.com/btccom/btcpool/issues/89

**Comment by awemany** [comment]
I like to point out that I also reserve extra space for the coinbase in my weakblocks code (#856) for the optional referencing with `OP_RETURN` to weakblocks. So if any code change that addresses this could also keep my use-case possible, that would be great :)

**Comment by sickpig** [comment]
Closed by #1278.
