### ISSUE TITLE
No Ubuntu 16.10 Yakkety packages for PPA

### ISSUE THREAD

**Issue by gsarrco** [gandrewstone/bitcoin#127]
There's [no package](https://launchpad.net/~bitcoin-unlimited/+archive/ubuntu/bu-ppa) of Bitcoin Unlimited for the last Ubuntu version 16.10.

**Comment by sickpig** [comment]
the Ubuntu repo provides packages for the last 2 LTS (14.04 and 16.04), 4 arch's (armhf, arm64, i386 and amd64).

this is the second request we received about providing debs also for 16.10.

I'll put it on my todo list hopefully I'll be able to work on it during the coming week.

**Comment by gsarrco** [comment]
Thank you very much!

**Comment by sickpig** [comment]
yeah the Ubuntu repo provide packages for last  2 LTS (14.04 and 16.04), 4
arch's (armhf, arm64, i386 and amd64).

this is the second request we received about providing debs also for 16.10.

I'll put it on my todo list hopefully I'll be able to work on it during the
coming week.

**Comment by sickpig** [comment]
@jacksarrocco sorry for the late notice but I'm glad to inform you that ubntutu repos are currently supporting ubuntu yakkety
