### ISSUE TITLE
Dev branch: bitcoin-miner causes an exception in rpc/mining.cpp

### ISSUE THREAD

**Issue by lonoami** [gandrewstone/bitcoin#1288]
In the dev branch (maybe others too):
The code below throws an exception when 
bitcoin-miner
asks for a mining candidate.

The msg recieved by bitcoin-miner: Support for 'testdummy' rule requires explicit client support

rpc/mining.cpp

`        case THRESHOLD_ACTIVE:
        {
            ...
        }
`

**Comment by ptschip** [comment]
@lonoami Can you give more information?  Did this happen every time you run?

**Comment by lonoami** [comment]
It happens every time. 
I'm running a debug build.
git: commit 74eb7ab7e4906a9d22989b3c87f763cf0bdf8d27
It did not happen when I implemented getmining candidate in june/2018.

`if (setClientRules.find(vbinfo.name) == setClientRules.end())`
`vbinfo.name` is "csv"

bitcoin.conf:
regtest=1
rpcuser=foo
rpcpassword=bar
server=1
mining.unsafeGetBlockTemplate=1

@ptschip can you please run:
src/bitcoin-miner

**Comment by ptschip** [comment]
i tried  gbt and getminingcandidate in regtest and they both failed...however, that was from an old regtest chain...when i created a new chain it worked just fine...I mined 144 blocks, did get block template... 
getblocktemplate
{
  "capabilities": [
    "proposal"
  ],
  "version": 536870913,
  "rules": [
  ],
  "vbavailable": {
    "csv": 0,
    "!testdummy": 28

**Comment by lonoami** [comment]
Good that it works. I'm closing this bug.
