### ISSUE TITLE
Full Node crashed overnight

### ISSUE THREAD

**Issue by ghost** [gandrewstone/bitcoin#133]
Regularly running a full node on and off. This most recent session had been on for a couple days. Woke up to this crash.

NOTE: My device still calls this Bitcoin-Qt because I had that install a long time ago, but this is BU. I'm not sure why my device labels it as such under the hood.

OSX El Cap 10.11.6 on an early 2009 Mac Pro.
2.66 GHz Quad-Core Intel Xeon
8 GB 1066 MHz DDR3 ECC
VIDIA GeForce GT 120 512 MB

[BU_crash.pdf](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/551650/BU_crash.pdf)

**Comment by ptschip** [comment]
OK, it doesn't break anything to take it out...I opened PR# 134

**Comment by sickpig** [comment]
@reillysmith which version of BU are you using? The one you get from bitcoinunlimited.info site or did you compile from source?

**Comment by rebroad** [comment]
@reillysmith please can you ensure you have command line option debug=net for future runs, and be sure to include the debug.log file if it crashes again - without this, it's a lot less likely to determine the cause.

**Comment by ghost** [comment]
Sorry, I did not keep up with this thread after posting. I just posted another crash that is probably similar.

@sickpig this is from bitcoinunlimited.info download.

@rebroad i'm a layman. could you clarify this instruction?

**Comment by gandrewstone** [comment]
several mac crashes have been found and fixed since this issue report.  We are now running continually on a mac machine, so I think that these have likely been fixed...

**Comment by sickpig** [comment]
@reillysmith I'm currently building osx binaries to test the code that will be the base for the coming release. If you are interested I could provide it to you to see they work better. if this is the case just send me an email. In any case a new release will be out soon.

**Comment by sickpig** [comment]
@reillysmith I'm currently building osx binaries to test the code that will be the base for the coming release. If you are interested I could provide it to you to see they work better. if this is the case just send me an email. In any case a new release will be out soon.
