### ISSUE TITLE
Build Question wallet_ismine.cpp weird include?

### ISSUE THREAD

**Issue by gubatron** [gandrewstone/bitcoin#1391]
At the start of `src/wallet/wallet_ismine.cpp` there's an include to a non-existent file `wallet_ismine.h`

https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/8081f56d4fc3eb888b1fd0bbf8f3d0fd38dc444b/src/wallet/wallet_ismine.cpp#L7

Is `wallet_ismine.cpp` somehow excluded from the build process? If so how? is it auto-generated with the Makefile based build?

(just trying to understand the build as I'm making a `CMakeLists.txt` for personal use and found this building issue, for now I'm just excluding this file from my build)

**Comment by awemany** [comment]
Heh, good catch! It looks like that file is completely unused and likely has been for a while. AFAICS, the parts in it have been renamed some time ago to `script/ismine.*`. I am very unfamiliar with the wallet code, however.

It doesn't look like it is part of any build process nor is it autogenerated. If so, it should be in `configure.ac` or any of the `Makefile.am`s or in a process that is called as a dependency. I am not aware of anything like that.

As far as I can see, it should be safe to remove it from the git.

This is the commit ID that moved it: c477d82a71c624f16f3020174eb3a12bdaab13eb

EDIT: It seems to have been accidentally included in this commit: 

2b6abf95eff33101309f4ea38e308c5d4cd06804

**Comment by gubatron** [comment]
Wohoo!
