### ISSUE TITLE
Activate SV features by default

### ISSUE THREAD

**Issue by monkeylord** [gandrewstone/bitcoin#1482]
As we all see ABC is changing it's code , adding checkpoint to service bitmain.
There's a question to ask, even though Roger is good, will bitmain leave rooms for BU to develop and to stay neutral?

Can we rely on the sole hash power switching from BTC and BCH?
Or can we rely on the the hash power who reject TXs as they will?

The goal of SV is firm, and at least Coingeek is an honest pool, and SV get 64M block now.

The ABC side is not honered. Why not activate SV features by default and end this bullshit hashwar?
The ecosystem need balances.

**Comment by monkeylord** [comment]
I'd like to show you a picture, about what bitmain is thinking.

Jiang Jiazhi (姜家志) who is in charge of bitmain's bitcoin client development said:

~~~
还有一个我想提醒人，社区一直存在一种思路就是多个开发团队竞争是好的。
这种想法的错误的根源在于，整个区块链行业都缺开发者，根本不可能找到第二个团队来竞争。
There's another reminder. The community always believe that competition between multi dev-team is good.
But this idea is wrong, for the whole bitcoin industry need developers, thus it is totally impossible to get a second team to compete.
~~~

![_20181120140907](https://user-images.githubusercontent.com/5557974/48754797-ed63ed80-eccd-11e8-9948-a543eac1603a.jpg)


Meanwhile, bitmain's IPO file shows that they pay 50k USD/year per developer.The five manger get 28,720 k USD total in half a year, more than the sum-up salary of its 840 developers.

~~~
上半年，比特大陆研发薪酬支出为 2093 万美元，平均这些研发工程师每人半年收入 2.49 万美元。这样算下来，比特大陆工程师平均年薪 5 万美元，约合 35万人民币左右。


相比之下，比特大陆薪酬收入最高的 5 位管理层成员，在今年上半年共领取了 2872 万美元薪酬，比 840 名研发工程师总薪酬支出都高！这 5 名管理层成员，平均每人上半年获得了 574 万美元的薪酬，约合 3900 万人民币。这仅仅是半年收入。
https://baijiahao.baidu.com/s?id=1612732544826904561&wfr=spider&for=pc
~~~

**Comment by Greg-Griffith** [comment]
At this time a majority of our users run on the client for the BCH chain. Due to BSV being the minority in terms of users it does not make sense to make that the default.

**Comment by monkeylord** [comment]
> At this time a majority of our users run on the client for the BCH chain. Due to BSV being the minority in terms of users it does not make sense to make that the default.

Your stance is appreciated.
Also, I believe that BU's code is much better than ABC's.
Did you notice ABC 0.18.5 ? I'd like to say that it's a change on consensus and not even compatible with November Upgrade. It shall be called a feature of continuous hard fork.
What do you think? Do you agree with the changes? Did they ask you before?


Is it what users want?
Is following such a chain responsible for users?

**Comment by Greg-Griffith** [comment]
This is not the place to debate the policy of another client, this is for issues with the BU client.
