### ISSUE TITLE
Travis failing due to old libbost on CentOS

### ISSUE THREAD

**Issue by dagurval** [gandrewstone/bitcoin#1655]
The centos travis build uses a boost version older than 1.55, while Bitcoin Unlimited is on v 1.66. This is the reason CI on #1645 is failing.

This problem was likely introduced in https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/1637

**Comment by Greg-Griffith** [comment]
this should be fixed now  (#1661 )

**Comment by dagurval** [comment]
Confirmed centos works with #1645 after rebase
