### ISSUE TITLE
Sendcmpct version check

### ISSUE THREAD

**Issue by imaginaryusername** [gandrewstone/bitcoin#1701]
Latest version 1.6.0 implemented sendcmpct, which seemed to break Bitcore and required a quick hack to fix; upon closer inspection it did not seem like sendcmpct did 70014 version check recommended per BIP152. Is that correct? 

Bitcore posts itself as version 70001; doing a version check before sending newer messages might avoid complications in the future as well.

**Comment by ptschip** [comment]
fixed in #1706

**Comment by sickpig** [comment]
fixed in #1706
