### ISSUE TITLE
BitcoinUnlimited sync BCH chain instead BTC

### ISSUE THREAD

**Issue by BoGnY** [gandrewstone/bitcoin#1709]
Anyone can help me?? Why BitcoinUnlimited sync BCH chain instead BTC???

**Comment by ptschip** [comment]
You downloaded the BCH version which are well supported.

We haven't put out a BTC release for quite some time but you can still
download one from the website. Just make sure to look under the
"Official Bitcoin (BTC) Release section

https://www.bitcoinunlimited.info/download

**Comment by BoGnY** [comment]
ok thanks
