### ISSUE TITLE
High Memory after -reindex

### ISSUE THREAD

**Issue by bill-mcgonigle** [gandrewstone/bitcoin#1735]
Hi,

I ran bitcoind with -reindex and when it was done memory usage had grown to over 3.7GB and stayed there while it operated as a normal node.

After a clean shutdown and restart the daemon operations were as expected but memory usage is just over 400MB.

**Comment by ptschip** [comment]
thats normal...when u reindex all the unspent  coins from each block are
saved in memory...this greatly speeds up reindex and ibd.
