### ISSUE TITLE
Windows wakes up from sleep

### ISSUE THREAD

**Issue by kFTY** [gandrewstone/bitcoin#178]
Same Issue as https://github.com/bitcoin/bitcoin/issues/8806
It can be fixed by https://github.com/bitcoin/bitcoin/pull/8899

**Comment by sickpig** [comment]
@KFTY thanks for the info. I think we should cherry pick core fix and include it in the next release.

**Comment by sickpig** [comment]
@gandrewstone @kFTY I've just submitted PR #185 that cherry pick core fix

**Comment by sickpig** [comment]
@kFTY #185 is supposing to fix this and has been merged. 

Could you please verify if you are able to reproduce the problem?
