### ISSUE TITLE
Building on OpenBSD

### ISSUE THREAD

**Issue by soeren-b-c** [gandrewstone/bitcoin#1796]
I'm trying to build BU on OpenBSD 6.5.

I run into a small problem when running `gmake`.

```
gmake
Making all in src
gmake[1]: Entering directory '/home/sbc/BitcoinUnlimited/src'
/usr/local/bin/python3 ../contrib/devtools/xversionkeys.py > /src/xversionkeys.h < ./xversionkeys.dat
/bin/sh: cannot create /src/xversionkeys.h: No such file or directory
gmake[1]: *** [Makefile:11240: xversionkeys.h] Error 1
```

I can get around this with the trick mentioned here:
https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/doc/build-unix-rpm.md

```
python3 ../contrib/devtools/xversionkeys.py > ./xversionkeys.h < ./xversionkeys.dat
```

The issue seems to be that somehow the `abs_top_builddir` variable isn't put into the Makefile by `autogen.sh`

**Comment by soeren-b-c** [comment]
I have a feeling something similar is going on with the `builddir` variable.

Later I run into an error refering to `/obj`. Looking at the Makefile that is properly supposed to refer to `$(builddir)/obj`

**Comment by sickpig** [comment]
@soeren-b-c interesting, probably you are onto something. will check

**Comment by soeren-b-c** [comment]
I have gotten a bit further now, but now the build fails with

```
util.cpp:329:9: error: use of undeclared identifier 'OPENSSL_cleanup'
        OPENSSL_cleanup();
        ^
2 warnings and 1 error generated.
gmake[3]: *** [Makefile:8000: libbitcoin_util_a-util.o] Error 1
gmake[3]: Leaving directory '/home/sbc/test2/BitcoinUnlimited/src'
gmake[2]: *** [Makefile:11969: all-recursive] Error 1
gmake[2]: Leaving directory '/home/sbc/test2/BitcoinUnlimited/src'
gmake[1]: *** [Makefile:3738: all] Error 2
gmake[1]: Leaving directory '/home/sbc/test2/BitcoinUnlimited/src'
gmake: *** [Makefile:711: all-recursive] Error 1
```

This is with the latest dev branch, after running
```
export AUTOCONF_VERSION=2.69 
export AUTOMAKE_VERSION=1.16
./autogen.sh
./configure --disable-wallet --with-gui=no CC=cc CXX=c++ MAKE=gmake
gmake
```

**Comment by soeren-b-c** [comment]
I'm not a openBSD native, but it would seem that openBSD ships with LibreSSL 3.0.2.

```
$ openssl version                                                   
LibreSSL 3.0.2
```
perhaps that is the root of my troubles? But I don't know what to do from here.

**Comment by ptschip** [comment]
did you install all the dependencies, see  folder  /doc/build-unix.md


02/11/2019 1:34 p.m., Søren Bredlund Caspersen wrote:

**Comment by ptschip** [comment]
sorry i guess, for you it would be /doc/build-openbsd.md and also you
can check /doc/dependencies.md



02/11/2019 1:34 p.m., Søren Bredlund Caspersen wrote:

**Comment by soeren-b-c** [comment]
It was indeed dependencies.
Finally got it working now. Thanks.
