### ISSUE TITLE
Wrong name in Windows notification area 

### ISSUE THREAD

**Issue by tl121** [gandrewstone/bitcoin#2]
In the windows notification area (Windows 7) there is an icon when BU is running.  Mousing on this icon shows the name "Bitcoin Core client".  (The larger Icon shown when a BU window is open is correctly labeled.)  FYI.  If this is a known problem with branding, I apologize for raising the issue.

**Comment by gandrewstone** [comment]
Probably fixed via https://github.com/gandrewstone/BitcoinUnlimited/commit/bffc279d06c18ad42a0e30ed3cb9fc393e49dd22
which was overall branding search/replace.  Need to validate on windows...

**Comment by tl121** [comment]
Thanks.  I'll check when a build is released for Windows.

**Comment by gandrewstone** [comment]
I will test it before closing...

**Comment by ptschip** [comment]
this has been fixed as far as i can tell...testing on windows 7 with the new 12.1 branch
