### ISSUE TITLE
Respect -maxconnections when determining max outgoing connections.

### ISSUE THREAD

**Issue by monsterbitar** [gandrewstone/bitcoin#2177]
I have configured my node with the following:

> maxconnections=750
> maxoutconnections=500

and during startup I get the following message:

```Reducing -maxoutconnections from 500 to 125, because this value is higher than max available connections.```

After some digging around I've found that in some cases BU respects my `maxconnections` setting, but in others it uses the hard-coded `DEFAULT_MAX_PEER_CONNECTIONS` directly.

I'm not sure if I have missed something as I don't have intimate knowledge with the codebase, but it seems to me that `DEFAULT_MAX_PEER_CONNECTIONS` should get overwritten by the `maxconnections` settings in all places.

The case I have found is:

```src/net.cpp:int nMaxConnections = DEFAULT_MAX_PEER_CONNECTIONS;```

An example of where it seems to respect the user setting can be found here:

```src/init.cpp:    int nUserMaxConnections = GetArg("-maxconnections", DEFAULT_MAX_PEER_CONNECTIONS);```

**Comment by Greg-Griffith** [comment]
what OS are you using? (not that i think this is OS dependent, but just in-case we need that info for some reason)

**Comment by monsterbitar** [comment]
```
# uname -a
Linux silverblood 4.19.86-gentoo #2 SMP Fri Dec 13 18:49:44 CET 2019 x86_64 AMD Ryzen 5 2400G with Radeon Vega Graphics AuthenticAMD GNU/Linux```

**Comment by Greg-Griffith** [comment]
thanks

**Comment by Greg-Griffith** [comment]
#2180 should fix this issue

**Comment by monsterbitar** [comment]
I can confirm that all symptoms I had related to this issue has been resolved.

I will try to push the limits and see where that gets me, if I get other issues I'll report them separately.
