### ISSUE TITLE
Should we include ElectrsCash in release tarballs?

### ISSUE THREAD

**Issue by dagurval** [gandrewstone/bitcoin#2182]
The release tarballs are usually the basis for creating distro-specific packages.

When building BU+ElectrsCash for Gentoo, @monsterbitar ran into issues where `make electrscash` would try to fetch sources via network, but network requests were disabled during build.

To make the bundle more distro packaging friendly, 
- Add ElectrsCash source code to release tarballs
- Add configure option `--with-electrscash` that also builds ElectrsCash

A problem with this:
Compilation of ElectrsCash will still want to fetch rust dependencies from the network, and we can't bundle all dependencies into BU source code tarball.

**Comment by dagurval** [comment]
Related issue #1966

**Comment by monsterbitar** [comment]
From the distros perspective, if the compilation checks for the dependencies before trying to fetch them, and the distro in question can resolve those dependencies on its own before installing the package, then that should not be a problem.

For example, in gentoo I could specify that if someone install bitcoin-unlmited with the electrum use flag, that would pull in different dependencies than installing it without the electrum use flag.

**Comment by sickpig** [comment]
Solved by adding the deterministic ElectrsCash binary to the deb packages.
