### ISSUE TITLE
Graphene seems to have become stuck on a valid block

### ISSUE THREAD

**Issue by discoltk** [gandrewstone/bitcoin#2247]
Running BU 1.8.0, found my BU node stuck on a block producing the error:

"ERROR: Merkle root for 000000000000000000b3c121d014c883dda97e6b35a440a57d1011b3bfa44bef does not match computed merkle root"

Restarted it and that block was processed normally.    I see this error string is in the graphene code.

Please let me know if there is anything else I can provide (sorry I don't have a stack trace or anything as I restarted already.)

**Comment by sickpig** [comment]
@discoltk thanks for notifying us about the problem.

> Restarted it and that block was processed normally. I see this error string is in the graphene code.

Interesting so restarting the nodes fixed the problem for you. Will look into it. 

>  I see this error string is in the graphene code.

This kind of error could be related to all 3 fast propagation techniques implemented in BCH Unlimited, i.e. xthin, graphene and compact blocks


One last thing which is mainly unrelated we are in the process of moving the development of all BU projects from github to gitlab, inf BCH Unlimited git repo has been moved to gitlab.com/bitcoinunlimited/BCHUnlimited , feel free to contact us there in the future. 

Unfortunately the [bot](https://github.com/apps/repo-lockdown) that should take care to notify user about that seems to be not working currently (will fix it).
