### ISSUE TITLE
libpng errors on start

### ISSUE THREAD

**Issue by Azulan** [gandrewstone/bitcoin#240]
I'm getting two libpng errors when launching qt from command line.

libpng warning : iccp: known incorrect sRGB profile
" " cHRM chunk does not match sRGB

**Comment by sickpig** [comment]
@Azulan does bitcoin-qt works despite of the two warnings?

**Comment by Azulan** [comment]
Yes.

**Comment by sickpig** [comment]
the warning is harmless, libpng is complaining about the iCCP section of a png image bundled in bitcoin-qt.

I'm going to check all of them so that we will a avoid the warning in the coming release

for more details see http://stackoverflow.com/q/22745076 for more detail.

**Comment by Azulan** [comment]
Still getting errors on 1.0.1.3.

**Comment by sickpig** [comment]
Closed by #487 for `dev`, #488 will be merged shortly in `release`
