### ISSUE TITLE
Compiling gives error "make[2]: *** [libbitcoin_server_a-main.o] Error 4"

### ISSUE THREAD

**Issue by ghost** [gandrewstone/bitcoin#244]
I'm trying to switch my node over to BU, but I'm running into errors on compilation. Any help is appreciated! I'm compiling this on bitnodes hardware running:

> bitnodes@bitnodes-hardware:~/src/bu-src$ cat /etc/lsb-release  
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=14.04
> DISTRIB_CODENAME=trusty
> DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"

I ran these commands for the install:

> $ mkdir -p ~/src
> $ cd ~/src
> $ git clone https://github.com/BitcoinUnlimited/BitcoinUnlimited.git bu-src
> $ cd bu-src
> $ git checkout bu0.12.1c
> $ ./autogen.sh
> $ ./configure --without-gui --without-miniupnpc --disable-wallet
> $ export NUMCPUS=`grep -c '^processor' /proc/cpuinfo`
> $ make -j$NUMCPUS

Here is the output from the last command (make) with errors:

> bitnodes@bitnodes-hardware:~/src/bu-src$ make -j$NUMCPUS
> Making all in src
> make[1]: Entering directory `/home/bitnodes/src/bu-src/src'
> make[2]: Entering directory `/home/bitnodes/src/bu-src/src'
>   CXX      libbitcoinconsensus_la-hash.lo
>   CXX      libbitcoinconsensus_la-pubkey.lo
>   CXX      libbitcoinconsensus_la-uint256.lo
>   CXX      libbitcoinconsensus_la-utilstrencodings.lo
> make[3]: Entering directory `/home/bitnodes/src/bu-src/src/secp256k1'
> gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
>   CXX      bitcoind-bitcoind.o
>   CXX      libbitcoin_server_a-addrman.o
>   CXX      libbitcoin_server_a-alert.o
>   CXX      libbitcoin_server_a-bitnodes.o
> gcc gen_context.o -o gen_context
> ./gen_context
>   CC       src/libsecp256k1_la-secp256k1.lo
>   CXX      libbitcoin_server_a-bloom.o
>   CCLD     libsecp256k1.la
> make[3]: Leaving directory `/home/bitnodes/src/bu-src/src/secp256k1'
>   CXX      libbitcoin_server_a-chain.o
>   CXX      libbitcoin_server_a-checkpoints.o
>   CXX      libbitcoin_server_a-httprpc.o
>   CXX      libbitcoin_server_a-httpserver.o
>   CXX      libbitcoin_server_a-init.o
>   CXX      libbitcoin_server_a-dbwrapper.o
>   CXX      libbitcoin_server_a-main.o
>   CXX      libbitcoin_server_a-merkleblock.o
>   CXX      libbitcoin_server_a-miner.o
>   CXX      libbitcoin_server_a-net.o
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
> make[2]: *** [libbitcoin_server_a-init.o] Error 4
> make[2]: *** Waiting for unfinished jobs....
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
> make[2]: *** [libbitcoin_server_a-main.o] Error 4
> make[2]: Leaving directory `/home/bitnodes/src/bu-src/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory `/home/bitnodes/src/bu-src/src'
> make: *** [all-recursive] Error 1

**Comment by ptschip** [comment]
can you try compiling with just "make"  and we'll see where it's really
failing.

what version are you trying to compile...we have a new release coming
out, it's the "release" branch...I would suggest you compile from that
source.

**Comment by ghost** [comment]
EDIT: Attached full make log: [make.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/706158/make.txt)

@ptschip i'm compiling bu0.12.1c. here is the last bit of the just make output as requested:

> make[3]: Entering directory `/home/bitnodes/src/bu-src/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CCLD     libsecp256k1.la
make[3]: Leaving directory `/home/bitnodes/src/bu-src/src/secp256k1'
  CXXLD    libbitcoinconsensus.la
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-addrman.o
  CXX      libbitcoin_server_a-alert.o
  CXX      libbitcoin_server_a-bitnodes.o
  CXX      libbitcoin_server_a-bloom.o
  CXX      libbitcoin_server_a-chain.o
  CXX      libbitcoin_server_a-checkpoints.o
  CXX      libbitcoin_server_a-httprpc.o
  CXX      libbitcoin_server_a-httpserver.o
  CXX      libbitcoin_server_a-init.o
  CXX      libbitcoin_server_a-dbwrapper.o
  CXX      libbitcoin_server_a-main.o
  CXX      libbitcoin_server_a-merkleblock.o
  CXX      libbitcoin_server_a-miner.o
  CXX      libbitcoin_server_a-net.o
  CXX      libbitcoin_server_a-noui.o
  CXX      policy/libbitcoin_server_a-fees.o
  CXX      policy/libbitcoin_server_a-policy.o
  CXX      libbitcoin_server_a-pow.o
  CXX      libbitcoin_server_a-rest.o
  CXX      libbitcoin_server_a-rpcblockchain.o
  CXX      libbitcoin_server_a-rpcmining.o
  CXX      libbitcoin_server_a-rpcmisc.o
  CXX      libbitcoin_server_a-rpcnet.o
  CXX      libbitcoin_server_a-rpcrawtransaction.o
rpcrawtransaction.cpp: In function 'UniValue sendrawtransaction(const UniValue&, bool)':
rpcrawtransaction.cpp:837:37: error: 'SyncWithWallets' was not declared in this scope
             SyncWithWallets(tx, NULL);
                                     ^
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
make[2]: *** [libbitcoin_server_a-rpcrawtransaction.o] Error 1
make[2]: Leaving directory `/home/bitnodes/src/bu-src/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bitnodes/src/bu-src/src'
make: *** [all-recursive] Error 1
bitnodes@bitnodes-hardware:~/src/bu-src$

**Comment by ptschip** [comment]
try compiling again but take out --disable-wallet

**Comment by ftrader** [comment]
I reproduced the 'SyncWithWallets was not declared in this scope' by using @patjnolan 's configure command on an Ubuntu 14.04.4 LTS system.

@ptschip 's suggestion of re-running the build with a configure command excluding the `--disable-wallet` option yields a working build on my test system.

**Comment by ptschip** [comment]
@freetrader  can you try to do the same with the "release"
branch...build with disable wallet..i believe we had fixed that issue
but can you check...

**Comment by ftrader** [comment]
@ptschip : the release branch builds OK with `--disable-wallet` . Unit tests show no errors.
rpc-tests refuse to run stating wallet must be enabled, which I believe is expected behavior.

So looks good...

**Comment by ptschip** [comment]
excellent, thanks.

**Comment by sickpig** [comment]
@patjnolan 

you following old instructions. Please check out branch `release` instead of `bu0.12.1c` and try to recompile again. 

`bu0.12.1c` is an outdated branch, please don't use it.

**Comment by ghost** [comment]
@sickpig @ptschip @ftrader Thanks for all the help guys, but I'm still getting compiling errors building the `release` branch, with and without the `--disable-wallet` option:

```
[...]
config.status: creating Makefile
config.status: creating pc/libunivalue.pc
config.status: creating pc/libunivalue-uninstalled.pc
config.status: creating univalue-config.h
config.status: executing depfiles commands
config.status: executing libtool commands
Making all in src
make[1]: Entering directory `/home/bitnodes/src/bu-src/src'
make[2]: Entering directory `/home/bitnodes/src/bu-src/src'
  CXX      libbitcoinconsensus_la-hash.lo
  CXX      libbitcoinconsensus_la-pubkey.lo
  CXX      libbitcoinconsensus_la-uint256.lo
  CXX      libbitcoinconsensus_la-utilstrencodings.lo
make[3]: Entering directory `/home/bitnodes/src/bu-src/src/secp256k1'
gcc -I. -g -O2 -Wall -Wextra -Wno-unused-function -c src/gen_context.c -o gen_context.o
  CXX      bitcoind-bitcoind.o
  CXX      libbitcoin_server_a-globals.o
  CXX      libbitcoin_server_a-addrman.o
gcc gen_context.o -o gen_context
./gen_context
  CC       src/libsecp256k1_la-secp256k1.lo
  CXX      libbitcoin_server_a-alert.o
  CCLD     libsecp256k1.la
make[3]: Leaving directory `/home/bitnodes/src/bu-src/src/secp256k1'
  CXX      libbitcoin_server_a-bitnodes.o
  CXX      libbitcoin_server_a-bloom.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make[2]: *** [libbitcoin_server_a-globals.o] Error 4
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/bitnodes/src/bu-src/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bitnodes/src/bu-src/src'
make: *** [all-recursive] Error 1
```

**Comment by dagurval** [comment]
I've seen this error if your box runs out of ram. Can you check `dmesg` and see if gcc was killed by the kernel?

**Comment by sickpig** [comment]
@patjnolan 

on which kind of machine (x86, arm,..)are you are compiling the source and which OS (Ubuntu, Debian...)? 

what's probably happening is that you are running out of memory and that linux OOM killer kicks in and kill the compiler. 

To be sure just after the falure try tu run this command form the command line: 

```
dmesg | grep -A 3 "Out of memory"
```

if as an output you see something like: 

```
Out of memory: Kill process XXXXX (cc1plus) score YY or sacrifice child
```

that means that you are effectively running out of memory while compiling from source. These what you can do to try to solve the problem: 

- try to reduce the number of `make` parallel jobs (e.g `make -j2` instead of `make -j4`)

- check if your machine swap area is activated. To verify this exec `free -m` cmd from a terminal. If swap is active the last line of the output must contains something like `Swap:    XXXXX  ....`. if not's active you could activated it using this simple guide: https://wiki.archlinux.org/index.php/swap#Swap_file

- compile a static binary on a bigger machine and deploy it on the smaller one. You could even cross-compile an ARM version on beefy X86_64 machine

**Comment by ghost** [comment]
@sickpig @ptschip @ftrader I compiled again with -j1, but still received the errors below. I'm compiling this on an ODROID-C1+, which has these specs:
* Amlogic ARM® Cortex®-A5(ARMv7) 1.5Ghz quad core CPUs 
* Mali™-450 MP2 GPU (OpenGL ES 2.0/1.1 enabled for Linux and Android)
* 1Gbyte DDR3 SDRAM
* Gigabit Ethernet
* 40pin GPIOs + 7pin I2S
* eMMC4.5 HS200 Flash Storage slot / UHS-1 SDR50 MicroSD Card slot

`At global scope:
cc1plus: warning: unrecognized command line option "-Wno-self-assign" [enabled by default]
  CXX      leveldb/table/leveldb_libleveldb_a-format.o
  CXX      leveldb/table/leveldb_libleveldb_a-iterator.o
  CXX      leveldb/table/leveldb_libleveldb_a-merger.o
  CXX      leveldb/table/leveldb_libleveldb_a-table_builder.o
  CXX      leveldb/table/leveldb_libleveldb_a-table.o
  CXX      leveldb/table/leveldb_libleveldb_a-two_level_iterator.o
  CXX      leveldb/util/leveldb_libleveldb_a-arena.o
  CXX      leveldb/util/leveldb_libleveldb_a-bloom.o
  CXX      leveldb/util/leveldb_libleveldb_a-cache.o
  CXX      leveldb/util/leveldb_libleveldb_a-coding.o
  CXX      leveldb/util/leveldb_libleveldb_a-comparator.o
  CXX      leveldb/util/leveldb_libleveldb_a-crc32c.o
  CXX      leveldb/util/leveldb_libleveldb_a-env.o
  CXX      leveldb/util/leveldb_libleveldb_a-env_posix.o
  CXX      leveldb/util/leveldb_libleveldb_a-env_win.o
  CXX      leveldb/util/leveldb_libleveldb_a-filter_policy.o
  CXX      leveldb/util/leveldb_libleveldb_a-hash.o
  CXX      leveldb/util/leveldb_libleveldb_a-histogram.o
  CXX      leveldb/util/leveldb_libleveldb_a-logging.o
  CXX      leveldb/util/leveldb_libleveldb_a-options.o
  CXX      leveldb/util/leveldb_libleveldb_a-status.o
  CXX      leveldb/port/leveldb_libleveldb_a-port_posix.o
  AR       leveldb/libleveldb.a
  CXX      leveldb/helpers/memenv/leveldb_libmemenv_a-memenv.o
  AR       leveldb/libmemenv.a
  CXXLD    bitcoind
libbitcoin_server.a(libbitcoin_server_a-unlimited.o): In function `scoped_lock':
/usr/include/boost/atomic/detail/lockpool.hpp:71: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
/usr/include/boost/atomic/detail/lockpool.hpp:71: undefined reference to `boost::atomics::detail::lockpool::get_lock_for(void const volatile*)'
collect2: error: ld returned 1 exit status
make[2]: *** [bitcoind] Error 1
make[2]: Leaving directory `/home/bitnodes/src/bu-src/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bitnodes/src/bu-src/src'
make: *** [all-recursive] Error 1`

**Comment by Justaphf** [comment]
@patjnolan I ran into this error (the boost atomic get_lock_for linker error) the other day while building the `release` branch from source on my Pi3 (also ARMv7 processor).  @sickpig was able to provide the solution to get it building on my Pi so hopefully it will work for you as well.

When you run your `configure` command, you should prepend `LIBS="-lboost_atomic"`.  So to modify your original configure command you would have:
`LIBS="-lboost_atomic" ./configure --without-gui --without-miniupnpc --disable-wallet`
Make sure it's all in one line when you execute the command.

**Comment by sickpig** [comment]
Closed per https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/244#issuecomment-275030178

**Comment by 88plug** [comment]
The build is sensitive to make -j$NUMCPUS

Remove any reference to make -j$(nproc) etc and you will be good to go.
