### ISSUE TITLE
Bitcoin-qt throws error when exiting

### ISSUE THREAD

**Issue by Azulan** [gandrewstone/bitcoin#246]
Using the latest ppa release on Ubuntu 16.10 x64, I receive a "closed unexpectedly" error every time I exit the program. I send reports every time, but I don't know if that helps you or not.

**Comment by sickpig** [comment]
try to use the nightly ppa repo, the binaries available from there should have this issue fixed: 

```
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:bitcoin-unlimited/bu-ppa-nightly
sudo apt-get update
sudo apt-get install bitcoind bitcoin-qt
```

**Comment by Azulan** [comment]
Resolved issue, but now the disk and network performance while syncing from local peer has degraded significantly.

**Comment by sickpig** [comment]
How did you measure the performance degradation? 

That said I'm going to update the nightly repo with the code in the `release` branch in an our. I'll let you know once is ready so that you could upgrade bitcoind and bitcoin-qt via apt and try again.

**Comment by Azulan** [comment]
Just subjectively. Before updating the release client was downloading and
syncing from a local fully synched peer at megabytes per second. After
installing the nightly, it's slowed to a megabyte every few seconds. I'll
update later to see if it improves. Thank you.

**Comment by ptschip** [comment]
it's typcial on a restart that at first performance is degraded .  that
is because the UTXO is no longer in RAM and it take a while for it to be
pulled in as new blocks are processed.   It ususally takes a few hours
until you regain best performance.  Also it depends on the size of you
database cache...the default is 300MB but you may set it higher/lower.

16/01/2017 6:06 AM, Frank Flores wrote:

**Comment by Azulan** [comment]
Yes, forgive me, I did alter the cache settings. It is now back to the previous level of performance. Thank you!

**Comment by ptschip** [comment]
no problem, thanks for taking the time to make a report.

**Comment by sickpig** [comment]
@Azulan I've updated the Ubuntu ppa nightly repo with binaries compiled from the same source we are going to use for the upcoming release. 

If you want to give it a try: 

```
apt-get update
apt-get upgrade
```

**Comment by sickpig** [comment]
Solved https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/246#issuecomment-272863660
