### ISSUE TITLE
1.0.0, block generation can exceed configured configured value depending on coinbase

### ISSUE THREAD

**Issue by gandrewstone** [gandrewstone/bitcoin#258]
The block generation in 1.0.0 is only reserving 100 bytes for the coinbase, but this can be exceeded (the reservation only takes into account the coinbase string, not the full tx).  This can cause blocks to exceed 1MB.  

As a workaround, run: ./bitcoin-cli setminingmaxblock 999000

Additionally, miners often take the block generated by getblocktemplate, remove the coinbase, and replace it with their own with a more complex payment.  So the space alloted to the coinbase should be configurable, and default to 1000 to match previous releases.

**Comment by ftrader** [comment]
Alternatively, you should be able to use the bitcoind command line option `-blockmaxsize=<n>` where n is the max block size in bytes, i.e. `-blockmaxsize=999000`, or set

`blockmaxsize=999000`

in your bitcoin.conf. This would make the workaround persistent across restarts of the daemon.
