### ISSUE TITLE
Testnet for BUIP001

### ISSUE THREAD

**Issue by Mirobit** [gandrewstone/bitcoin#290]
Why is there no testnet for BUIP001/Emergent Consensus? Segwit was tested in 4 different testnets.

BU miners are already signalling for a hard fork that has never been tested. Correct me if I am wrong but BU needs a proper testnet.

**Comment by ftrader** [comment]
Run `bitcoind --help`, and refer to the section `Chain selection options`:

```
  -testnet
       Use the test chain

  -chain_nol
       Use the no-limit blockchain
```

Specifically, BU has its own testnet - the no-limit (nol) network.

**Comment by zander** [comment]
Additionally -testnet-ft on Classic has various > 1MB blocks.

**Comment by gandrewstone** [comment]
closed, not a bug.
