### ISSUE TITLE
main.cpp:4857: void ProcessGetData(CNode*, const Consensus::Params&): Assertion `!"cannot load block from disk"' failed.

### ISSUE THREAD

**Issue by soeren-b-c** [gandrewstone/bitcoin#293]
I can trigger my node to crash by running a new node and force it to -connect only to my full node.
The full node then crashes with this error in the console:

bitcoin-qt: main.cpp:4857: void ProcessGetData(CNode*, const Consensus::Params&): Assertion `!"cannot load block from disk"' failed.

the debug.log has this:
ERROR: ReadBlockFromDisk: Deserialize or I/O error - ReadCompactSize(): size too large at CBlockDiskPos(nFile=27, nPos=64059636)

t could be a hardware error on my end (don't hope so), but I don't experience other strange crashes or similar.

As said, it is fairly reproducible, if you need additional info.

**Comment by ptschip** [comment]
can you give more detail on how you can reproduce this?

also, is your full node running fine before you try to connect, by that
i mean are you receiving new blocks and storing them to disk?  and where
are you connecting from?  any detail would be helpful. thanks

**Comment by soeren-b-c** [comment]
I just start a "new" node on the same lan, and start it with -connect=10.0.0.126 (my full node ip on the lan).
The new node starts fetching from block #1 and after a few minutes, my full node crashes.

The full node works fine when I don't do this.

**Comment by ptschip** [comment]
sounds like you have a disk issue , but what version of BU are you running?

**Comment by soeren-b-c** [comment]
Version: v1.0.0.0-ac26645

That's bad news for me, but good news for the code i guess...
Thanks for your time.

**Comment by ptschip** [comment]
you might want to try and see if you can reproduce the same issue using
a version of Classic or Core etc...

also, what system are you running on?

**Comment by soeren-b-c** [comment]
Will try to reproduce with others.

It's Ubuntu 16.04
16 gb ram
Intel® Core™ i5-4590 CPU @ 3.30GHz × 4 
450 gb ssd disk

**Comment by ptschip** [comment]
oh, it's an ssd...that may be the problem, but try the Classic or Core
node as a verification.

**Comment by soeren-b-c** [comment]
I tried Classis, and found same problem.
Also found this old thread:
https://github.com/bitcoin/bitcoin/issues/5668

From what I gather the blocks have been corrupted (somehow), and only solution is to fetch all again. So that is what I'm doing now...
Let's see if it works.

**Comment by gandrewstone** [comment]
disks suffer from rare large failures,  SSDs suffer from more common single
byte or bit failures.  Don't delete the bad file (mv it to a different
directory on the same disk though).  That should keep the bad bits consumed
in this now-unused file.  But of course, your SSD might have other
failures...

**Comment by lonoami** [comment]
I have the same problem.
version v1.0.0.1-dda0c0e 
Ubuntu 14.04.5 LTS

The tail of the log is below. Let me know if you want the complete log & some .dat files.


2017-03-12 19:31:04 BLOCK_DOWNLOAD_WINDOW is 8 MAX_BLOCKS_IN_TRANSIT_PER_PEER is 1
2017-03-12 19:31:04 Pre-allocating up to position 0x5000000 in blk00801.dat
2017-03-12 19:31:04 UpdateTip: new best=000000000000000000e8bf12549623d3dc6de180534da714961da5dbe4635e2f  height=456951  log2_work=86.114635  tx=204178069  date=2017-03-12 19:30:21 progress=1.000000  cache=136.7MiB(61071tx)
2017-03-12 19:31:04 UpdateTip: 21 of last 100 blocks have unexpected version. One example: 0x20000002
2017-03-12 19:31:10 Acceptable block: ver:20000000 time:1489347021 size: 997955 Tx:1783 Sig:2969
2017-03-12 19:42:42 Acceptable block: ver:20000002 time:1489347750 size: 998240 Tx:1938 Sig:3496
2017-03-12 19:42:42 BLOCK_DOWNLOAD_WINDOW is 8 MAX_BLOCKS_IN_TRANSIT_PER_PEER is 1
2017-03-12 19:42:43 UpdateTip: new best=000000000000000001c2ee842cf6ef8b1d94ffd3be2402304c5e14962ef6436f  height=456952  log2_work=86.114669  tx=204180007  date=2017-03-12 19:42:30 progress=1.000000  cache=142.9MiB(64667tx)
2017-03-12 19:42:43 UpdateTip: 22 of last 100 blocks have unexpected version. One example: 0x20000002
2017-03-12 19:43:01 Acceptable block: ver:20000002 time:1489347750 size: 998240 Tx:1938 Sig:3496
2017-03-12 19:53:25 ERROR: ReadBlockFromDisk: Deserialize or I/O error - ReadCompactSize(): size too large at CBlockDiskPos(nFile=520, nPos=1996385)

**Comment by ptschip** [comment]
are you running on an SSD by any chance ?

also upgrade to 1.0.1 and then tell us what happens on restart...but it
sounds more like a disk error to me.

if no change after restart you'll probably have to re-index.

**Comment by lonoami** [comment]
Yes SSD. 
I will try what you suggest.

On another note:
It would be interesting to see what part of the file(s) is corrupt. Do all file errors end up with the same assertion? Etc.

I'm going to use a mechanical HD from now on :-)

**Comment by ptschip** [comment]
ssd's are not a good option for bitcoin...they tend to suffer .

**Comment by sickpig** [comment]
PIVX shared the same code as BU and they fix an issue like this one with this PR https://github.com/PIVX-Project/PIVX/pull/88

They were able to reproduce the blockchain data corruption repeatedly killing (-9) the main process. 

Wonder if we could use such changes to avoid this kind of corruptions also in BU

**Comment by sickpig** [comment]
@soeren-b-c you said here https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/293#issuecomment-278998123 
that you think you got your on-disk block corrupted for some reasons and you were tyring to refetch it from the net. Were you able to do it? If this is the case, was the issue fixed?

**Comment by soeren-b-c** [comment]
@sickpig I ended up re-downloading all the blocks.

I can't reproduce the crash now, so for me the issue was fixed. Guess we will never know if it was hardware or software failure.

Thanks for your time.
