### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by rem0g** [gandrewstone/bitcoin#369]
Add a feature for participants with BU-node to signal Segwit + EB/AD values in coinbase.

The code is ready to go and can be reduplicated from this merge: 
https://github.com/bitcoin/bitcoin/pull/7910

**Comment by gandrewstone** [comment]
a feature this large cannot be trivially merged.  And this idea needs to be voted on by the membership.  Please submit a BUIP on bitco.in rather than open a bug.  Thanks!
