### ISSUE TITLE
Please denounce untrue and defamatory claims being made in your projects name.

### ISSUE THREAD

**Issue by gmaxwell** [gandrewstone/bitcoin#374]
In many places on the internet parties are claiming that the recent shutdown of BTU nodes was due to actions by Bitcoin Core. Many of these comments have been made by regular supporters of your project and members of the Bitcoin Unlimited organization.

One of the more extreme examples of these remarks and the articles they inspire is: http://archive.is/y7KSA
which goes on to attribute comments by some anonymous nobody that has never been anywhere near Core AFAICT to an actual person that has had nothing to do with this stuff.

You are in a unique position to silence some of this abuse, earn yourself some goodwill, and protect your organization from culpability for the actions of some of your more foolish members.

**Comment by jmdugan** [comment]
gmaxwell: you no longer have standing to request anything in the Bitcoin community.  

You've led a multi-year campaign to co-opt and take over Bitcoin with actions, comments and software design choices that support your for-profit company (Blockstream), in direct conflict with the interests of miners, users, investors and everyone else connected to Bitcoin.  This project (BitcoinUnlimited) and many others have been created specifically to stop the greedy, selfish intentions driving your actions, and the actions of your co-developers on "Core".

Online my chat included someone just yesterday that was told BU was an "altcoin" and that if BU gained 51% hash power, everyone would lose their coins.  These are the lies being told by your supporters.

GO AWAY.  Your actions and positions as de-facto leader of "Core" leads anyone who begins even a cursory evaluation of facts to conclude that YOU are the leader of abusers, not the recipient.

Seriously, you need to QUIT THE BITCOIN COMMUNITY, ENTIRELY: you and "Core" are no longer welcome.  Pick a new line of work, a new project; find you path, somewhere else. Your action are antithetical to the long-term success of the Bitcoin community.

**Comment by Alex-Linhares** [comment]
Oh Boy... Perhaps Mr. Maxwell would like to start with the wikipedia people calling him a vandal?

**Comment by gmaxwell** [comment]
> You've led

I have? Where?

> co-opt and take over Bitcoin

Since when? The Bitcoin project has substantially the same major contributors since 2011... thats a pretty long con you're alleging.

> with actions, 

What actions? Be specific.

> comments

So I'm not free to speak my mind when you disagree with me?

> that support your for-profit company

Can you cite a single example?

> direct conflict with the interests of miners, users, investors and everyone else connected to Bitcoin

Can you cite a single example?

> Online my chat included someone just yesterday that was told BU was an "altcoin" 

It would be a kinder interpretation of BU to say that, the alternative is that it wishes to force a fundamental change to Bitcoin onto people against their will.

> and that if BU gained 51% hash power, everyone would lose their coins. 

Are you sure that is what they said?  Many people, myself included, would expect a serious loss of value Bitcoin in such an event-- as it is basically a blueprint for disruption by powerful actors... but most people won't directly lose their coins (except as a result of replay issues, which the BU project has been working to block others from fixing, according to the forums).

If it really was saying they'd lose their coins outright, point me at it and I'll go tell 'em that its wrong.

> Your actions and positions as de-facto leader of "Core" 

I am not the leader of the Bitcoin project or the Bitcoin Core software, something you might know, if you made even "a cursory evaluation of facts".

But facts are something your message is completely devoid of, instead it's a wall of insults, attacks, defamation, and unsubstantiated conspiracy theories-- exactly the sort of thing BU should be calling out if it has any integrity.

> : you and "Core" are no longer welcome.

We were using and building Bitcoin a hell of a lot longer that you were.

Is it really the case that I can't comment here about attacks on other people without myself being hit with a bunch of personal attacks?

**Comment by gmaxwell** [comment]
Wow. I just saw that the unlimited organization faked screenshots, cutting out 0.13.2 -- hiding the move from nodes from one version to another-- to support the claim of a vulnerability existing that simply didn't exist.

https://i.imgur.com/mCq9Jhq.gif

(From this writeup: http://archive.is/syO9v )

The actual data on bitnodes now sure as heck doesn't support anything in those obviously doctored shots: https://bitnodes.21.co/dashboard/?days=90

Moreover, it supposedly took these screenshots proporting to show some kind of phantom Bitcoin Core crash... on the 7th, but didn't bother sending an email to Bitcoin Core until the 11th.

I'm going to go ahead and close this. I have no hope in ethical behavior from any of you.
