### ISSUE TITLE
master branch

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#376]
The 'master' branch is usually HEAD for development, but not in BU and this is highly unique. Is there a reason for that?

I think there's at least potential for confusion and although this is a minor issue, it might still be good (if there is no good reason for the current setup) to deal with this/fix it/make it as usually expected everywhere else.

Branch mechanics left the pruning fix on the wrong branch for the release AFAICS, so I think making things similar / more streamlined would be a good idea here (to cut down on the potential for confusion). Principle of least surprise and all that.

It is also somewhat of a  public relations issue, as the master branch is what initially comes up on github when I look at the repo and people might falsely conclude that there is no development going on.

**Comment by nfujimoto** [comment]
I am also recently thinking about the development model. See issues #378. If you agree, please give a vote.

**Comment by AllanDoensen** [comment]
I do not know the reason why the devs did that here... but when you have two 'masters' in git it often gives you grief when working from a forked project where both projects are still active. IMHO leaving master on core and having release/dev on BU makes complex merging and cherry-picking easier.

**Comment by sickpig** [comment]
@awemany 

I agree with you and to your point I would add BU has another peculiarity: the default branch is not the one where the development is going on. In fact BU github default branch is `release` not `dev`. 

@gandrewstone decided that way on both points and he being the lead developer has the power to do it. 

I have no strong opinion about the name of the development branch, I could live with `dev` but I think this deviation from the "convention over configuration" principle could be quite misleading for new project.

On the other hand not having `dev` as default branch could give the wrong impression about dev process pace. Tools and sites (e.g https://coin.dance/nodes#allNodes) will just grab the default branch to show the last commit.

**Comment by sickpig** [comment]
@gandrewstone could please say what's your stance on this issue so that we can move on?

**Comment by sickpig** [comment]
closing for lack of feedback form @gandrewstone, @awemany please reopen it it if you think appropriate.
