### ISSUE TITLE
Unsigned GIT tags 

### ISSUE THREAD

**Issue by emanuelb** [gandrewstone/bitcoin#388]
Several GIT tags are not signed (missing Verified), see:
https://github.com/BitcoinUnlimited/BitcoinUnlimited/tags
https://github.com/BitcoinUnlimited/BitcoinUnlimited/releases/tag/1.0.1.1
https://github.com/BitcoinUnlimited/BitcoinUnlimited/releases/tag/bu0.12.1c

fix:
always sign GIT tags, as correctly done in Bitcoin core:
https://github.com/bitcoin/bitcoin/tags

**Comment by sickpig** [comment]
@gandrewstone I could be valuable for you to add your GPG public key to your github account and use it to sign tags, with a little bit of conf you can use it also to sign all your commits.

**Comment by sickpig** [comment]
@gandrewstone 

https://help.github.com/articles/signing-tags-using-gpg/
https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work#_signing_tags

closing. 

@emanuelb please reopn if you noticed that we are not going to sign all the newly created tag from now on.
