### ISSUE TITLE
xthin bugfixes made in Classic.

### ISSUE THREAD

**Issue by zander** [gandrewstone/bitcoin#391]
I want to point you guys to some fixes I made in Classic to the xthin code (mostly just the network-facing code).

See; https://github.com/bitcoinclassic/bitcoinclassic/commit/b185d5f4485a4e3327ce603bd61939d2805747bd

**Comment by sickpig** [comment]
@ptschip did we cover this issue already with #468 and #436 ?

**Comment by sickpig** [comment]
closed by #450, #468
