### ISSUE TITLE
Remitano exchange want to support Bitcoin Unlimited, what should we do?

### ISSUE THREAD

**Issue by phuongnd08** [gandrewstone/bitcoin#397]
We want to help pay great developer to contributing to Bitcoin Unlimited. Could you BitcoinUnlimited organizer let us know how we can help?

**Comment by ftrader** [comment]
Thank you very much for contacting Bitcoin Unlimited with this very helpful offer.

Please contact info@bitcoinunlimited.info for an invitation to our Slack Chat to discuss further.

**Comment by gandrewstone** [comment]
closed, we are in contact.
