### ISSUE TITLE
Devops: Add coverity scan

### ISSUE THREAD

**Issue by kristovatlas** [gandrewstone/bitcoin#421]
COVERITY SCAN STATIC ANALYSIS

- Find and fix defects in your Java, C/C++, C#, JavaScript, Ruby, or Python open source project for free
- Test every line of code and potential execution path.
- The root cause of each defect is clearly explained, making it easy to fix bugs
- Integrated with GitHub

Bitcoin Core is already using this in some fashion: https://scan.coverity.com/projects/bitcoin

FAQ: https://scan.coverity.com/faq

**Comment by sickpig** [comment]
@kristovatlas thanks for the suggestion we are working on it!
