### ISSUE TITLE
Mempool saving feature between restarts

### ISSUE THREAD

**Issue by ghost** [gandrewstone/bitcoin#438]
Bitcoin core 0.14 has a mempool saving feature that saves the mempool states between restarts. This is a very useful feature for people who multiboot between O/S's. (and also in the event of a system crash for miners.) I think this would be useful to add to BU.
I am not familiar with this part of the code, but I would look to implement the transaction pool in a virtual memory segment using mmap(), msync(), munmap() if possible. This would mean that all transactions are immediately loaded into virtual memory on start up when the memory segment is mapped onto.

**Comment by ghost** [comment]
I have opened similar issues on Classic and XT:

https://github.com/bitcoinclassic/bitcoinclassic/issues/251
https://github.com/bitcoinxt/bitcoinxt/issues/195

So far zander has provided some insights and thoughts on this issue, which are certainly worth considering.

**Comment by ghost** [comment]
gmaxwell as outlined the idea behind this feature.

https://bitcointalk.org/index.php?topic=1864311.0

**Comment by stefment** [comment]
gmaxwell is the boss

**Comment by bill-mcgonigle** [comment]
This is done?

```
2019-05-17 01:13:00 Dumped mempool: 0.006519s to copy, 0.091756s to dump
2019-05-17 01:15:40 Imported mempool transactions from disk: 1460 successes, 0 expired
```

**Comment by ptschip** [comment]
yes, this was ported over from Core.  It's configurable so you can turn
it off if you wish.

**Comment by sickpig** [comment]
closing as per https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/438#issuecomment-493291704
