### ISSUE TITLE
bitcoind crash when connect ipv6 address

### ISSUE THREAD

**Issue by CryptoZ258** [gandrewstone/bitcoin#440]
when connect to ipv6 address, bitcoind crash, traceback:
connect() to [2620:101:80fc:224:2327:96bb:70fb:bb1c]:18333 failed: Cannot assign requested address

**Comment by ptschip** [comment]
did you try to manually connect using the -connect option or was this
some external node trying to connect to you?

that looks like a testnet port, are you trying to connect to testnet? 
we have a different testnet called nol which uses port 9333

**Comment by ptschip** [comment]
also can you tell me what version you're running?

**Comment by CryptoZ258** [comment]
the version is v1.0.1.2, yes, I am work with testnet, when I found this issue, I add onlynet=ipv4 to avoid ipv6 connect.

**Comment by CryptoZ258** [comment]
It maybe cause by my oom problem, not the bitcoind problem, when out of the memory, the bitcoind crash.

**Comment by joshafest** [comment]
Can anyone join the contributer team and make pull ?

**Comment by ftrader** [comment]
@joshafest : yes, for sure.

**Comment by sickpig** [comment]
@bibodeng could please verify if the crash was due to OOM killing bitcoind (`/var/log/kern.log`)?

**Comment by sickpig** [comment]
closing for lack of feedbacks, issue not reproducible. @bibodeng feel free to reopen in case you are still experiencing the problem.
