### ISSUE TITLE
Fix Norton flagging BU as malware. (Possible fix.)

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#441]
https://www.reddit.com/r/Bitcoin/comments/64wpt8/comment/dg5ryzp

**Comment by ftrader** [comment]
That doesn't seem like a link to a possible fix, unless I'm missing something.
The problem seems to be that Norton is diagnosing the installer as malware.

@sickpig : can you confirm that chainstate obfuscation is fully merged? I came out confused from that Reddit thread.

**Comment by sickpig** [comment]
@freetrader it is

**Comment by sickpig** [comment]
Suggested fix was for the false alarm triggered by the blockchain file. This one seems related to the windows installer executable. closing.
