### ISSUE TITLE
zesty development?

### ISSUE THREAD

**Issue by Azulan** [gandrewstone/bitcoin#448]
Wondering if/when there will be a build for the Ubuntu 17.04 PPA.

**Comment by sickpig** [comment]
Zeisty 17.04 will be the next Ubuntu LTS, we are going to add it to our PPA repo as soon as it will be released. Usually new ubuntu versions are released at the end of the month so I think we need to wait another few days.

**Comment by Azulan** [comment]
It's already released. I just upgraded to it.

**Comment by sickpig** [comment]
Really great didn't now about it. So that means that we will add Zeisty to our in a day or two. Thanks for the notice. 

edit: in the meantime you could use the binaries you could find at bitcoinunlimited.info/download

**Comment by sickpig** [comment]
@Azulan Ubuntu PPA repo now support Zesty
