### ISSUE TITLE
Memory usage grown to 5GB

### ISSUE THREAD

**Issue by ffallah** [gandrewstone/bitcoin#459]
Hi,
bitcoind memory usage has grown to 5.2GB after 1 month of running.
I restarted it and memory usage went down to 380MB.
is it normal or there is some kind of memory leak ?

**Comment by ftrader** [comment]
@ffallah : can you share some more details:
- parameters used (esp. if you set dbcache or mempool / connection-related params)
- full node or pruned?
- OS platform

Thanks

**Comment by ffallah** [comment]
I am running bitcoind (latest version) x64 binary by following command :
bitcoind -daemon -datadir=/data/bitcoin -txindex -rpcuser=x -rpcpassword=x
full node
Debian 8.0 x64
I also run a public ElectrumX server which connects to this bitcoind instance, so there are probably a ton of rpc calls made to this bitcoind instance.

**Comment by kyuupichan** [comment]
I run ElectrumX with BU too :)

I run dev HEAD not release, but I haven't noticed anything unusual.  On a Mac it reports 2.8 GB used after 3 days, but "compressed memory" (I think RSS) of 900MB which seems OK.

Are you looking at RSS?

**Comment by kyuupichan** [comment]
@ffallah are you on #electrum?  Which server do you run?

**Comment by ffallah** [comment]
I am looking at RES (RESIDENT) memory size reported by top.
it has gone from 380MB to 600MB in 3 hours. Is it caching something in memory ?
Are BitcoinUnlimited and BitcoinCore databases compatible ? I may try to switch clients to see if I experience the same issue on core as well or not.

**Comment by ffallah** [comment]
Yes I am, I run electrumx.adminsehow.com

**Comment by kyuupichan** [comment]
Ah cool.  Sure, please try core and let us know if you see a difference, that would be a valuable test.

**Comment by ffallah** [comment]
I switched to BitcoinCore, memory usage is 290MB now. I'll report back how it goes.

**Comment by ffallah** [comment]
Core memory usage has grown to 700MB in 7 hours. memory usage growth is definitely slower than Unlimited. but I am wondering, is there any limit to it ? or it's going to continue until it crashes the system.

**Comment by kyuupichan** [comment]
You're running at the weekend when mempool empties. Keep running until Wednesday for a fair comparison

**Comment by DesWurstes** [comment]
Also: https://www.reddit.com/r/btc/comments/6726w8/comment/dgn5kac

**Comment by nomnombtc** [comment]
Can also confirm high memory usage since around 10 days or so, before it was pretty flat.

And around an hour ago I had two bitcoind's die because of oom. Those servers each have 16GB ram, and I even restarted one of the nodes yesterday. They both crashed within a minute according to my monit email ( 07:06 CEST and 07:07 CEST ) ... Both are running 1.0.1.3. 

Edit: One of the also runs ElectrumX the other doesn't.

**Comment by deadalnix** [comment]
@nomnombtc There is a new bug in XThin. You may want to build with PR 468 and try that.

**Comment by nomnombtc** [comment]
@deadalnix yeah I patched one node with this PR already, but wasn't 100% sure this is the correct one, somehow it has a lot more changes than the fix that went into bitcoinclassic earlier today :) But it compiles fine and node is up and running :+1:

**Comment by ffallah** [comment]
I have switched to core for now. memory usage has increased from 700MB to 885MB in 2 days. if it keeps increasing, it means core also has memory leak issues.

**Comment by sickpig** [comment]
@ffallah this is being fixed by #468 (backport to `release` of  #450) and included in BU ver 1.0.1.4
