### ISSUE TITLE
1mb txn push

### ISSUE THREAD

**Issue by 1mbtxn** [gandrewstone/bitcoin#464]
Would the BU team like to create a version that allows for this txn to be pushed to the network? 
Current version does not appear to allow for a large txn to push. 

Results in error, -26: 64: tx-size

https://paste.ee/p/vbH5J
https://www.reddit.com/r/btc/comments/6747e2/1mb_fork_txn/

**Comment by ftrader** [comment]
I'm having trouble understanding why BU should make changes to allow such transactions to be pushed.

If they are mined into a block, they would be propagated anyway (at least by nodes which don't consider >1MB blocks automatically invalid).
Interested miners could already obtain the transaction from your link.

Allowing such huge transactions to be pushed could in my opinion result in attacks through similar huge transactions. There seems no benefit in allowing such huge transactions right now.

A miner that wants to build a > 1MB block to fork the network can do so already (doesn't even need this transaction). Just needs the support of enough hashpower (with or without this tx).

**Comment by sickpig** [comment]
Closing.

**Comment by sickpig** [comment]
Since https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/465 is still open and refer back to this issue we are going to leave this issue open for another week or two, hoping that someone else chime in

**Comment by rcawston** [comment]
It seems the only reason to merge this (or #465) would be to attempt to introduce consensus incompatibility with other clients. The link in 1mbtxn's comment suggests this is exactly the intent.

NACK

**Comment by sickpig** [comment]
Closing
