### ISSUE TITLE
make check fails

### ISSUE THREAD

**Issue by atisharma** [gandrewstone/bitcoin#474]
For the latest release branch (I think equivalent to tagged 1.0.1.4), make check fails (log attached). Compiled from source with
`./configure --prefix=/usr/local --disable-wallet --without-gui`

Debian stretch,
`uname -a`
`Linux vostok 4.9.0-1-amd64 #1 SMP Debian 4.9.6-3 (2017-01-28) x86_64 GNU/Linux`

[test-suite.log.txt](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/955117/test-suite.log.txt)

**Comment by ftrader** [comment]
I saw similar reverselock_tests failures on Debian 7 and Ubuntu 16.10 (both x86_64), but it tested fine for me on Debian 8 x86_64 .

The failures appear to be related to Boost somehow: this is an extract from Debian 7:

```
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >' 

what():  boost unique_lock owns already the mutex: Resource deadlock avoided test mining with different sized miner comments

unknown location(0): fatal error: in "reverselock_tests/reverselock_errors": signal: SIGABRT (application abort requested)
```

**Comment by sickpig** [comment]
@atisharma not able to reproduce this failure on a Debian `strecth` distro with current `release`, could you please update us and tell us if `release` is still failing for you? Thanks

**Comment by atisharma** [comment]
I upgraded release, recompiled and it's still failing for me.

**Comment by sickpig** [comment]
@atisharma care to test it again with the latest version of `release` @ 7e94f2e ? 

It would be great also to know if you are able to reproduce the problem using the `dev` branch

**Comment by sickpig** [comment]
closing for lack of feedback and cause I'm not albe to reproduce. @atisharma  feel free to reopen in case you have more info.
