### ISSUE TITLE
Wallet disabled in pruned nodes

### ISSUE THREAD

**Issue by nmag** [gandrewstone/bitcoin#5]
I run a pruned node and I need the wallet, but pruning disables by default the wallet. Wallet works in the latest version of core, but I couldn't find the appropriate commit, which enables the wallet in pruned nodes. Maybe someone could find and merge this commit?

**Comment by sickpig** [comment]
@nmag 

@gandrewstone rebased BU branch integrating Core 0.12 changes. So I think that you could use BU in pruned node and having a working wallet. See: 

https://bitcoin.org/en/release/v0.12.0#wallet-pruning

Could please if the latest version of BU fix the problem for you and if this is the case close the issue? 

thanks

**Comment by sickpig** [comment]
@gandrewstone I think the issue has been fixed after the last rebase we made, we could close it now and reopen it if @nmag will experience again the same issue

**Comment by nmag** [comment]
@sickpig Thanks for the update. I gave up the project with the pruned node, so I can't test it atm. However, as soon as I find some time I will give it a try again.

Since it has been rebased, I don't think there is any reason that the wallet is not working any more. Maybe the issue should be closed now...

**Comment by sickpig** [comment]
@gandrewstone this issue should be closed

**Comment by ftrader** [comment]
I'm slightly confused about which release has fixed this problem. We should try to identify that better in closing actions.
