### ISSUE TITLE
Error when compiling against latest openssl (1.1.0e)

### ISSUE THREAD

**Issue by SjonHortensius** [gandrewstone/bitcoin#503]
Probably related to https://mta.openssl.org/pipermail/openssl-dev/2016-January/004143.html

```
wallet/crypter.cpp: In member function ‘bool CCrypter::Encrypt(const CKeyingMaterial&, std::vector<unsigned char>&)’:
wallet/crypter.cpp:62:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
wallet/crypter.cpp: In member function ‘bool CCrypter::Decrypt(const std::vector<unsigned char>&, CKeyingMaterial&)’:
wallet/crypter.cpp:89:20: error: aggregate ‘EVP_CIPHER_CTX ctx’ has incomplete type and cannot be defined
     EVP_CIPHER_CTX ctx;
                    ^~~
make[2]: *** [Makefile:5540: wallet/libbitcoin_wallet_a-crypter.o] Error 1
```

**Comment by sickpig** [comment]
@SjonHortensius openssl 1.1 support has been merged into `dev` branch. `release` does not support it.

**Comment by SjonHortensius** [comment]
okay, awesome!

**Comment by tuxayo** [comment]
As a user, what can be done to help 1.1 support to land in the `release` branch?

I though about running the `dev` branch but with 140 commits behind and 1300 commits ahead `release`, I'm afraid that there will be data changes and will prevent going back to `release` without having to redownload the blockchain. Is such a fear justified?

**Comment by gandrewstone** [comment]
there are no data changes.  You can switch between dev and release just by running the different binary.

**Comment by tuxayo** [comment]
Great, I will try the dev branch and report any issue. Is there anything else that can be done?

**Comment by tuxayo** [comment]
Are there known issues that prevent this going to the ~~dev~~ release branch? Because it's still doesn't build against latest openssl (1.1.0.f)

**Comment by tuxayo** [comment]
Oops, I meant release branch
