### ISSUE TITLE
Enhancement: Use an updated app icon.

### ISSUE THREAD

**Issue by JasonLeeH** [gandrewstone/bitcoin#539]
Maybe it's just me, but the current Bitcoin Unlimited app icon looks like it was designed with Windows Vista in mind:

![Current Logo](https://i.imgur.com/LBuegai.png)

I've made an icon which looks great on both Windows 10 and macOS. 

**How it looks on macOS:**

![App Icon](https://i.imgur.com/Cwitk61.png)

**Hi-Res version:**

![Hi-Res](https://i.imgur.com/MreEb50.png)

**Comment by sickpig** [comment]
I rarely use bitcoin-qt so I could be wrong, but hasn't the BU app ico has the infinity symbol at the bottom?

**Comment by JasonLeeH** [comment]
@sickpig Yes, but Bitcoin is Bitcoin so it doesn't really make sense to differentiate on branding, especially if we are to insist Bitcoin Unlimited _is_ Bitcoin.

**Comment by sickpig** [comment]
closing due to lack of interest in changing the logo. @JasonLeeH feel free to reopen a new issue to lobby more to get the logo changed if you think it is worthy.

**Comment by JasonLeeH** [comment]
Just wanted to point out that the logo is now being used on the website: ![New Logo](https://www.bitcoinunlimited.info/img/bitcoin-unlimited.png)
