### ISSUE TITLE
In the 'release' branch looks like a regression appeared wrt xthin blocks

### ISSUE THREAD

**Issue by zander** [gandrewstone/bitcoin#543]
The code is supposed to behave in such a way that when a transaction from the xthin block is missing from a node's mempool, it will request the missing transactions using NetMsgType::GET_XBLOCKTX

Looking at the code in the release branch, this functionality has been unintentionally removed with the introduction of the `fMerkleRootCorrect` variable.

This is because when a transaction is missing, that means that this line is executed;

`fullTxHashes.push_back(mapPartialTxHash[cheapHash]);`

which will have two effects, it will create a new entry in the mapPartial (unwanted memory usage(1)) and it will push an empty full hash in the list.  
The most important part is that in case a transaction is missing, fMerkleRootCorrect is guaranteed to be false.

Then when we look further, the code falls back to a thinblock when the fMerkleRootCorrect is false. And it never manages to reach the code that does the request for more transactions.

1] http://www.cplusplus.com/reference/map/map/operator[]/
> If k does not match the key of any element in the container, the function inserts a new element with that key and returns a reference to its mapped value.

**Comment by gandrewstone** [comment]
Sorry for the confusion this is intentionally removed right now so xthinblock state is not held.  This makes certain mem exhaustion attacks harder.  We will reenable when we have given our xthin mem limiter some runtime.
