### ISSUE TITLE
getnetworkinfo() RPC call does not return all thinblock info

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#546]
More specifically, in rpc/net.cpp, GetThinBlockStats() the push_backs of multiple times summary let the values in the dict overwrite each other.

This is for the current dev branch. Found it while implementing a thinblock.py rpc-test.

I am going to make a PR for this issue right now.

**Comment by ftrader** [comment]
Confirmed by code inspection https://github.com/BitcoinUnlimited/BitcoinUnlimited/blob/dev/src/rpc/net.cpp#L440

Issue exists also on 'release' branch.

**Comment by ftrader** [comment]
@sickpig : this bugfix (PR https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/547 ) needs a backport to release.

**Comment by sickpig** [comment]
thanks for the notice, I'm going to add the appropriate label.

**Comment by sickpig** [comment]
closed by #547
