### ISSUE TITLE
Memory leak suspicions when downloading many blocks to catch up

### ISSUE THREAD

**Issue by tuxayo** [gandrewstone/bitcoin#558]
Context:
- I had few days of lag.
- I switched to dev branch on commit ef180ce0e

Bitcoind was killed twice due to out of memory issues. Which didn't happen during few month of using the release branch.

I updated (to commit 0969d1c1a as the time) to maybe fix the issue.

The download of the remaining blocks finished without crashing. (I suspect that it caught up enough during the previous run so that this one didn't had the time to crash.)

But Bitcoind was using way more RAM than usually. 1100MiB vs 600-750 from what I unreliably remember.

Now I just relaunched it and it uses only 450MiB.

I'm waiting more time to reach a stable value and confirm that the high RAM usage were remains of block downloads.(which would indicate a leak right?)

So, is there more info that I can provide? Because this isn't much :(

**Comment by sickpig** [comment]
@tuxayo 
since a bunch of other commits went in since 0969d1c, could you please retry with `dev` at the current HEAD (8bd89c3)? Thanks in advance.

**Comment by tuxayo** [comment]
Ok, it's building.

So, after checking logs, the first OOM crash happened when catching up with only 5 hours of blocks. So it's easily testable.

My memory was wrong, it seems that ~1100 MiB of RAM usage after more than one day is pretty normal. So I suspect that when updating to 0969d1c already solved the issue as it had to catch up with more than 9h of blocks.

**Comment by tuxayo** [comment]
Can't reproduce. Is it of any use downgrading to ef180ce to confirm the initial leak ?
