### ISSUE TITLE
transactions in orphan pool

### ISSUE THREAD

**Issue by KlausT** [gandrewstone/bitcoin#574]
After a break of some days I started BU 1.0.2.0 about 2 hours ago.
I can see that there's a limit of 2500 transactions in the orphan pool.
My node is already hitting this limit while having <20000 transactions in the mempool.
`{
  "size": 18212,
  "bytes": 14324950,
  "usage": 36496800,
  "maxmempool": 700000000,
  "mempoolminfee": 0.00000000
}`
Is this expected?

**Comment by ptschip** [comment]
yes it's normal...with mempools backed up so much you will see a lot of
orphans just after startup...after 4 hours or so you should see the
number start to come down and within about 8 hours it should be much
lower...typical numbers are between 100 and 300 but with mem pools
backed up so much i'm still seeing them between 1500 to 2000.

**Comment by ptschip** [comment]
if you manually want to adjust the max number of orphans use 
-maxorphantx=<num> to set it higher/lower.

**Comment by ptschip** [comment]
to give you an expectation...i have one node started two days ago...num
txns in mempool is 158,000, num orphans is 769,  another node started 12
hours ago has 90K txns and 2326 orphans.  Usually it wouldn't take so
long for the orphan pool to normalize but as i said with these backed up
pools it's taking longer.




13/05/2017 11:08 AM, KlausT wrote:
