### ISSUE TITLE
Only downloading several megabytes after hours and hours of operation

### ISSUE THREAD

**Issue by Azulan** [gandrewstone/bitcoin#575]
After running the client for over 10 hours, it only downloaded 9 megabytes of data. After updating to latest version 1.0.2, after 4 hours, only 3 megabytes have been downloaded. There are only ever 1 to 3 peers connected at a time. Is this common or normal?

**Comment by ftrader** [comment]
This is not normal. I started a sync with 1.0.2.0 a day or so ago recently and I have about 8 peers and downloaded several gigabytes already (my machine is very slow at processing).

May I suggest that you use the RPC 'addnode' command to add some more peers from the list of BU nodes at https://bitnodes.21.co/nodes/?q=BitcoinUnlimited (bottom of the page lists active nodes).

Also, I usually feel free to 'disconnectnode' peers that have UASF in their useragent string (as seen in 'getpeerinfo' RPC output), and replace them with other nodes.

You may want to check if you have a bitcoin.conf file with unwanted settings, or if you have a banlist.dat that is preventing large ranges of the network from peering with you.

**Comment by sickpig** [comment]
@Azulan #629 has ben ported to `release` via #639 
Could you please check if the problem has been fixed using the latest version of `release`? 
thanks

**Comment by sickpig** [comment]
Closing for lack of feedback. @Azulan feel free to reopen in case you are able to reproduce on a recent versin of `release`
