### ISSUE TITLE
Remove jgarzik DNS seed

### ISSUE THREAD

**Issue by dgenr8** [gandrewstone/bitcoin#576]
While adding the BU DNS seeder to XT https://github.com/bitcoinxt/bitcoinxt/pull/200 we were reminded that @jgarzik DNS seed was removed with reason: "Unlike the other seeds, this one is just a static list of IPs that was compiled years ago and now all but one IP is dead. Having it in the list is therefore useless."

**Comment by jgarzik** [comment]
ACK

**Comment by sickpig** [comment]
@dgenr8 @jgarzik thanks for the notification! Going to prepare a PR to remove it from BU list of seeders.
see: #577

**Comment by sickpig** [comment]
@dgenr8 are you planning to set up a seeder maintained by the XT project?
