### ISSUE TITLE
QA: "bool collision" variable in CXThinBlock::process() hides one from outer scope, no default value

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#585]
In CXThinBlock::process(..), the "bool collision" variable ironically collides with the one in the outer, class wide scope.

This is worked around with "this->" logic. A cleaner approach would be to use separate names.

Furthermore, no default value for the class-wide variable is given in the default constructor.

**Comment by ptschip** [comment]
this will be fixed in PR #603

**Comment by sickpig** [comment]
#603 has been merged, closing
