### ISSUE TITLE
Bitcoin Core still showing up in some places

### ISSUE THREAD

**Issue by ptschip** [gandrewstone/bitcoin#59]
The publisher when you look in Uninstall Program shows up as Bitcoin Core...probably a few of those still lurking in the code.

**Comment by Justaphf** [comment]
Saw this today while reading CONTRIBUTING.md under the "Decision Making" Process section:

> The following applies to code changes to the Bitcoin **Core** project (and related projects such as libsecp256k1), and is not to be confused with overall Bitcoin Network Protocol consensus changes.
> 
> Whether a pull request is merged into Bitcoin **Core** rests with the project merge maintainers and ultimately the project lead.

And the last line in the file:

> The project leader is the release manager for each Bitcoin **Core** release.

**Comment by sickpig** [comment]
@ptschip, since #80 has been merged I think we should close this issue. 
I've checked the current branch and I didn't find any left over.

**Comment by ptschip** [comment]
sounds fine with me.

**Comment by sickpig** [comment]
cool. I can't close it now due to lack of auth. 
ping @gandrewstone. Or maybe you as an owner could close it, I'm not sure though.

**Comment by sickpig** [comment]
@gandrewstone this issue should be closed

**Comment by ptschip** [comment]
closing
