### ISSUE TITLE
test_bitcoin: key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.

### ISSUE THREAD

**Issue by error10** [gandrewstone/bitcoin#595]
I'm attempting to build BitcoinUnlimited 1.0.2.0 on Fedora 24, which includes GCC 6.3.1.

While the code appears to compile correctly, `make check` fails on `test_bitcoin`. The `test-suite.log` shows 87 test failures, all with this particular assertion failing. A representative sample:

```
terminate called without an active exception
Running 203 test cases...
test mining with different sized miner commentsunknown location(0): fatal error:
 in "reverselock_tests/reverselock_errors": signal: SIGABRT (application abort r
equested)
test/reverselock_tests.cpp(51): last checkpoint
test_bitcoin: key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign =
= NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_rawparams": signal: SIGABRT 
(application abort requested)
test/rpc_tests.cpp(56): last checkpoint: "rpc_rawparams" fixture entry.
test_bitcoin: key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign =
= NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_rawsign": signal: SIGABRT (a
pplication abort requested)
test/rpc_tests.cpp(98): last checkpoint: "rpc_rawsign" fixture entry.
test_bitcoin: key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign =
= NULL' failed.

...


*** 87 failures are detected in the test module "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)
```

The failure occurs on both 32-bit and 64-bit. The 64-bit configuration is:

`'--build=x86_64-redhat-linux-gnu' '--host=x86_64-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib64' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-reduce-exports' '--enable-glibc-back-compat' 'build_alias=x86_64-redhat-linux-gnu' 'host_alias=x86_64-redhat-linux-gnu' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'PKG_CONFIG_PATH=:/usr/lib64/pkgconfig:/usr/share/pkgconfig' --disable-shared --with-pic --with-bignum=no --enable-module-recovery`

The 32-bit configuration is:

`'--build=i686-redhat-linux-gnu' '--host=i686-redhat-linux-gnu' '--program-prefix=' '--disable-dependency-tracking' '--prefix=/usr' '--exec-prefix=/usr' '--bindir=/usr/bin' '--sbindir=/usr/sbin' '--sysconfdir=/etc' '--datadir=/usr/share' '--includedir=/usr/include' '--libdir=/usr/lib' '--libexecdir=/usr/libexec' '--localstatedir=/var' '--sharedstatedir=/var/lib' '--mandir=/usr/share/man' '--infodir=/usr/share/info' '--enable-reduce-exports' '--enable-glibc-back-compat' 'build_alias=i686-redhat-linux-gnu' 'host_alias=i686-redhat-linux-gnu' 'CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables' 'PKG_CONFIG_PATH=:/usr/lib/pkgconfig:/usr/share/pkgconfig' --disable-shared --with-pic --with-bignum=no --enable-module-recovery`

The problem appears to be identical to https://github.com/bitcoin/bitcoin/issues/8260 which was resolved in 0.13.0.

**Comment by sickpig** [comment]
@error10 chance you could try to reproduce using 1.0.3 or cash 1.1.1.1?

**Comment by sickpig** [comment]
Closing. @error10 feel free to reopen if you are able to reproduce w/ current version.
