### ISSUE TITLE
dev branch new parameters validation does not allow "tweaks" in bitcoin.conf

### ISSUE THREAD

**Issue by gandrewstone** [gandrewstone/bitcoin#637]
Add this to your bitcoin.conf:
net.excessiveAcceptDepth = 6

output:
Error reading configuration file: unrecognized option 'net.excessiveAcceptDepth'

**Comment by kyuupichan** [comment]
output from what?  bitcoin-cli?  bitcoind?

**Comment by kyuupichan** [comment]
Reproduced; it seems to accept it on the command line directly, but not in the conf.

**Comment by sickpig** [comment]
closed by #638
