### ISSUE TITLE
Headers arriving out of order leading to banning of peer (bad-prev-blk)

### ISSUE THREAD

**Issue by ftrader** [gandrewstone/bitcoin#645]
Observed during testing of https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/642 that sometimes, peers are banned with a 'bad-prev-blk' reason.

I have observed similar bans on some regtests which fail (I think some of the currently Disabled ones in the extended suite, but also bip9-softforks on occasion).

@ptschip has indicated that this banning issue is known, but I'm raising it so further findings can be documented here and correlated with other issues.

**Comment by ftrader** [comment]
Possible fix:

https://github.com/BitcoinUnlimited/BitcoinUnlimited/pull/646

**Comment by sickpig** [comment]
@ftrader #646 has been merged, could you please try to see if the issue persist?

**Comment by ptschip** [comment]
should be fixed in PR650.

**Comment by sickpig** [comment]
@ftrader as @ptschip #650 has been merged in `dev` (and hence into `BitcoinCash`). 

This has being merged into `release` via #695 and it has been included in BU 1.0.3.

closing.
