### ISSUE TITLE
Segregated witness.  (#91 redux)

### ISSUE THREAD

**Issue by gmaxwell** [gandrewstone/bitcoin#688]
Historically, forks of Bitcoin Core (such as Bitcoin Classic, and Bitcoin XT) have fallen far behind on updates to network consensus behavior and that BU has fallen far behind on general development.

I noticed that BU doesn't have a ticket to implement segwit and doesn't appear to have started on implementation. The segwit proposal and consensus rules have been stable for over a year now, and implementation in core is complete and getting the final little bit of preactivation tweaks and improvements. Segwit been active and testing well on testnet for well over year... 

Segwit is specified in the following documents:

https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki
https://github.com/bitcoin/bips/blob/master/bip-0145.mediawiki
and implemented in Bitcoin Core: bitcoin#8149

Previously, the President of BU-- Andrew Clifford-- [stated](https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/91#issuecomment-261794834) that the elected and oath swearing members of BU would be given the ability to choose segwit if and only if a majority of nodes and hash power were segwit enabled.  This arbitrary and absurd bar has [now](http://luke.dashjr.org/programs/bitcoin/files/charts/services.html) been [met](http://bitcoin.sipa.be/ver9-2k.png).

Cheers,

**Comment by krisives** [comment]
Depends on if Andrew considers the two separate Segwit proposals as equal.

**Comment by microguy** [comment]
No one wants the blasphemous segwit code ruining Bitcoin.

**Comment by chacham18** [comment]
Seems legit

**Comment by digitsu** [comment]
Feel free to propose a BUIP like everyone else.
You need at least one member to sponsor it though.

**Comment by RubenSomsen** [comment]
@digitsu Easier said than done. Would you be willing to sponsor such a BUIP?

**Comment by digitsu** [comment]
The point of the rule that requires non members to require a member sponsor
is to prevent a potential flood of BUIP proposals being submitted that none
of the membership support, preventing spam attack on the governance
process. As I would not support this, your best course of action would be
to find a supporting member by opening a discussion on the bitco.in forums.
Conversely you could pursue becoming a member yourself.

**Comment by RubenSomsen** [comment]
@digitsu Are you of the opinion that this segwit BUIP would be a spam attack on the governance process? If not, then sponsoring it does not go against your stated reason for requiring a sponsor. Please elaborate.

**Comment by theslagter** [comment]
fuck these people

**Comment by gmaxwell** [comment]
Barring some kind of extraordinary reorg event or likewise BU will not be compatible, mining wise at least, with the rules enforced on the Bitcoin network at block 481824.

**Comment by gmaxwell** [comment]
Segwit is now locked in and will activate.  Since it appears that BU will not upgrade you should probably note that this software is not suitable for use by Bitcoin miners. Failure to do this might result in miners who mistakenly use your software losing money. Perhaps you should disable GBT?
