### ISSUE TITLE
Missing protocol documentation for xthin

### ISSUE THREAD

**Issue by zander** [gandrewstone/bitcoin#70]
The Classic team has been trying to implement xthin for some time now and has for about 2 months stalled due to lack of xthin protocol documentation.

To interoperate between clients we need actual documentation of the messages, their contents and enum values of invs etc etc etc.

I would really like to release Classic with support for xthin (the code has been there for some time). But without being able to review if I'm doing it correctly, its not really something I can release.

Keeping protocol changes in sync by copying each other's code is not an option ;)

In the mean time compact blocks has been released, it looks like xthin has missed its window of opportunity.

Sorry if this sounds rather negative, but most people on the project know I've been asking for months for this.

**Comment by ptschip** [comment]
it's on my todo list tom..we've been sidetracked with some urgent
issues..i'll be getting on to it tomorrow.

**Comment by ptschip** [comment]
@zander just opened pr72, much is done but still have a few things to fill in.  I'll let you know when it's done.

**Comment by ptschip** [comment]
@zander I've updated  PR72 xthin protocol doc..i think it's ready to be looked at.  If you have questions or think anything is missing or needs changing let me know...

**Comment by sickpig** [comment]
I think we should close this issue. Xthin protocol specification has been merged (see PR #72).
