### ISSUE TITLE
Seeds too Blockstream-ish

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#700]
Only two of 7 seeds are no-relationship-with-Blockstream.

How about adding [Bitcoin ABC seeds](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/src/chainparams.cpp#L172-L184) and [Segwit2x client seeds](https://github.com/btc1/bitcoin/pull/74/files)?

**Comment by sickpig** [comment]
Good Idea, I'll prepare a patch for it (if you don't beat me to it)

**Comment by ftrader** [comment]
@sickpig: Vice versa, if there is going to be special BU seeder for the UAHF / Bitcoin Cash chain, ABC would probably be happy to include that too.

Right now we are pointing at BU's general seeder (thanks btw!)

**Comment by DesWurstes** [comment]
How about letting the user choose which seeds to connect?

**Comment by sickpig** [comment]
Closing  due to changes applied to `BitcoinCash` branch. the current list of seeder on that branch is: 

    btccash-seeder.bitcoinunlimited.info
    seed.bitcoinabc.org
    seed-abc.bitcoinforks.org
    seed.bitprim.org
    seed.deadalnix.me

On the standard branched we didn't tocuh the list of seeders.
