### ISSUE TITLE
connections to Xthin capable nodes

### ISSUE THREAD

**Issue by KlausT** [gandrewstone/bitcoin#702]
I have updated to 1.0.3 some minutes ago.
In the release notes it says:

> Increase the minimum number of outgoing connections to 12 the minimum number of Xthin capable nodes to 8

I guess it doesn't work like I think it works, because I have only 3 Xthin capable nodes in the list:
![screenshot](https://i.imgpile.com/nwPv5N.jpg)
Could someone explain this for noobs like me?

**Comment by sickpig** [comment]
@KlausT 

it took some time to achieve the goal, and it's not even certain cause it could be that among all you peers there's not enough BU/Classic/XT clients.

Try this: Stop bitcoin-qt,  delete your `peers.dat` file and restart bitcoin-qt.

**Comment by KlausT** [comment]
ok, never mind, It's 9 now.

**Comment by sickpig** [comment]
great, closing.
