### ISSUE TITLE
Will the BitcoinCash branch be merged into the relase one?

### ISSUE THREAD

**Issue by tuxayo** [gandrewstone/bitcoin#717]
Or will there be two maintained stable branches?

I'm wondering if I should switch [this package](https://aur.archlinux.org/packages/bitcoind-unlimited-git) to follow the BitcoinCash branch or if I should create another one for the BitcoinCash branch and leave that main one on what would be the BTC branch.

**Comment by gandrewstone** [comment]
there will be 2 branches
