### ISSUE TITLE
BUcash transaction sequence number

### ISSUE THREAD

**Issue by discoltk** [gandrewstone/bitcoin#719]
Transactions made with BUcash 1.1.0 have a sequence number of 4294967294.    Why is this?   Should it not be 4294967295?

**Comment by gandrewstone** [comment]
The idea is to set nLockTime to the current block to discourage miner fee sniping (because nlocktime is only valid if nSequence < max).  This looks like common code in all Satoshi clients...

**Comment by discoltk** [comment]
@gandrewstone Please check my question more carefully.  

Normally nSequence is set to maxint.   2^32 is 4294967296 (0 - 4294967295).

My code to catch RBF-enabled transactions was triggered by BUcash because nSequence is < 4294967295.   It's setting it to 4294967294 instead of 4294967295.

**Comment by gandrewstone** [comment]
@discoltk please read the comment in  CWallet::CreateTransaction about fee sniping, and then examine this code a bit further down:
                // Fill vin
                //
                // Note how the sequence number is set to non-maxint so that
                // the nLockTime set above actually works.
                for (const auto& coin : setCoins)
                    txNew.vin.push_back(CTxIn(coin.first->GetHash(),coin.second,CScript(),
                                              std::numeric_limits<unsigned int>::max() - 1));

If you look at similar code in core you'll see that rbf is maxint-2:

                // Fill vin
                //
                // Note how the sequence number is set to non-maxint so that
                // the nLockTime set above actually works.
                //
                // BIP125 defines opt-in RBF as any nSequence < maxint-1, so
                // we use the highest possible value in that range (maxint-2)
                // to avoid conflicting with other possible uses of nSequence,
                // and in the spirit of "smallest possible change from prior
                // behavior."
                bool rbf = coinControl ? coinControl->signalRbf : fWalletRbf;
                for (const auto& coin : setCoins)
                    txNew.vin.push_back(CTxIn(coin.first->GetHash(),coin.second,CScript(),
                                              std::numeric_limits<unsigned int>::max() - (rbf ? 2 : 1)));

**Comment by discoltk** [comment]
@gandrewstone  Thanks kindly for explaining.

The only issue I can see with this is that if the other clients are setting it to max(), it means that the client used to generate the transactions are loosely identifiable.   I don't think there's too much that can be done with that info, just a bit uncomfortable leaking any info unnecessarily.   Checking a random sampling of transactions, I'm seeing about half with max() and half with max()-1.   Perhaps your apparently more nuanced consideration of this should be added to the technical spec so that other wallet developers fall in line.

Best and thanks for your hard work on BU!

**Comment by gandrewstone** [comment]
sure, you're welcome!  I'd be interested in hearing stats about how many RBF tx there are on the network and how many RBF tx actually get replaced if your work can produce this data.
