### ISSUE TITLE
BUCash: Incredible slow initial sync, how long will it take?

### ISSUE THREAD

**Issue by Commenter123** [gandrewstone/bitcoin#730]
My sync with `Bitcoin Unlimited Version bucash1.1.0.0 (64-Bit)` is already running for more than two days.
Around 380.000 blocks are still left (~ 50%), the last received block is about 2 years old. The debug window shows 12 incoming connections.
I have a quad core CPU, 16 GB of RAM, SSD and a 12 MB/s (symmetric) internet connection. I have restarted Bitcoin Unlimited every 12 hours.

Why is it so slow? How can I speed it up? Will the whole initial download of the blockchain really take _at least_ 4 days with optimal hardware?

**Comment by Commenter123** [comment]
I've read that upstream (Bitcoin Core) version 0.14.0 speeds up syncs around 50%. Is the patch already integrated into this repo?

**Comment by Commenter123** [comment]
Sorry, should have looked up the command line options. Simply increasing the default 12 outgoing connections already helped a lot 😆

**Comment by gandrewstone** [comment]
You can also increase the dbcache to speed thing's up a LOT

**Comment by Y2PM** [comment]
Can you explain how you did those things to speed it up? When I try the -maxoutconnections=<n> command it just says command not found.

**Comment by gandrewstone** [comment]
For example

bitcoind -dbcache=2000
