### ISSUE TITLE
Reset Options can lose wallet/blockchain?

### ISSUE THREAD

**Issue by BillStrait** [gandrewstone/bitcoin#737]
I downloaded Bitcoin Unlimited and threw a few bch on it and imported a private key. Then I started playing around with the options. I went to update the 'Third party transaction URLs,' was prompted that the client needed to be restarted for the changes to take effect. I saw a button that said 'reset options,' so I clicked it. I saw another prompt that warned 'Client restart required to activate changes. Client will be shut down. Do you want to proceed?' Which sounds exactly like what I want to do.

Then I restart the client and discover my wallet has been overwritten, and apparently I need to resync the blockchain. So... that's not cool. Shame on me for not backing up my wallet first thing. 

In troubleshooting this I realized I probably have Bitcoin Unlimited installed when I meant to have Bitcoin Unlimited Cash. Maybe that contributed to my wallet's death?

**Comment by gandrewstone** [comment]
The wallet should never be overwritten, but a resync is not a wallet overwrite.  Are you resyncing or redownloading?  If redownloading, it seems like your entire .bitcoin subdirectory was deleted (did you do anything in the interim that could have caused that?).  If resyncing, your wallet is likely still intact, even if the balance being shown on the GUI is currently 0 (it will go up once you get to the block the confirmed your tx).

EDIT: if you sent BCC to a BTC address, your BTC wallet will never show a balance.  Luckily they are the same wallet, so if you just use it in a BCC context, you'll see your funds.  Back up your wallet now by copying ~/.bitcoin/wallet.dat somewhere.  Next, install BU cash on some other machine and copy the wallet.dat to ~/.bitcoin/wallet.dat. When BU cash syncs, you should see your funds.

**Comment by BillStrait** [comment]
Thanks for leaving this open. I'm not sure what I did, and I've spent the last ~4 months trying to figure it out. Whatever happened it was probably caused by user error.
