### ISSUE TITLE
Feature REQ: Coin Freeze option to "Send transaction"

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#750]
It can be done with nLockTime
![](https://cloud.githubusercontent.com/assets/4302362/18002742/f186a4ce-6b89-11e6-93b4-28e11059e98e.png)
![](https://cloud.githubusercontent.com/assets/4302362/18002785/3e4315fe-6b8a-11e6-877a-266c54213f86.png)

Images: @gercio https://github.com/bitcoin/bitcoin/issues/8431

**Comment by sickpig** [comment]
It can be done with nLockTime also in BUcash 1.1.1.0

![itcanbedone](https://user-images.githubusercontent.com/1469203/29278887-50635d3c-8116-11e7-8314-c9bd7bc90fd0.png)

**Comment by sickpig** [comment]
Closing

**Comment by DesWurstes** [comment]
Can I use it to send bitcoins to an address I don't own?
