### ISSUE TITLE
Change/Remove alert keys/system

### ISSUE THREAD

**Issue by gmaxwell** [gandrewstone/bitcoin#76]
Your project contains the old centralized "alert" system previously copied from upstream Bitcoin. This system lets the holders of a private key send messages to be displayed in the error field. Because of its limited utility, potential for abuse, known disclosure of the key to at least one untrustworthy party (and is believed to be compromised), and frequent use to justify other centralizing features this system has long been deactivated (and now is completely removed) upstream.

I would recommend you remove this system by adopting this code from upstream: https://github.com/bitcoin/bitcoin/pull/7692 or the parallel PR in bitcoin xt, https://github.com/bitcoinxt/bitcoinxt/pull/150

Can you please let me know when you plan to release a version replaces the key or removes the system entirely? Thanks.

**Comment by gandrewstone** [comment]
A member proposed the removal of the alert system in early January 2016 in BUIP013.  This BUIP was voted to be adopted in late January and was implemented very soon thereafter.  So the alert system has been removed for two releases.

**Comment by gmaxwell** [comment]
Okay. Thanks! (My issue-open was driven because the code and keys are still in the codebase of your latest release.)

**Comment by rebroad** [comment]
@gmaxwell Any reason not to divulge details of the compromise or the untrusted party? I think this information would help with the risk assessment.
