### ISSUE TITLE
[Consensus] Problems with difficulty drop consensus rule

### ISSUE THREAD

**Issue by ser81** [gandrewstone/bitcoin#761]
[https://github.com/Bitcoin-ABC/bitcoin-abc/issues/75](url)
If my understanding of Blockchain is correct, the nessesary changes can be done by a Soft Fork.
How will the decision be made whether to make the appropriate adjustment in BCH-chain code or not?

**Comment by sickpig** [comment]
this is a matter you should bring up and discusso on Bitcoin Cash related mailing list: https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-ml
