### ISSUE TITLE
Possible "OP_Return" bug?

### ISSUE THREAD

**Issue by DesWurstes** [gandrewstone/bitcoin#765]
If I choose to send my Bitcoin Cashes to more than one addresses, then there are multiple "Public Label" boxes.

![screen shot 2017-08-30 at 11 40 22](https://user-images.githubusercontent.com/23437045/29863499-8b4498da-8d78-11e7-95ce-0e99a017f20f.png)

There should be only one "Public Label" box as only one `OP_return` is allowed per transaction.

**Comment by sickpig** [comment]
@DesWurstes you are right indeed.

**Comment by marlengit** [comment]
I don't think this is a bug. The OP_RETURN output is associated to the amount of the *following* output. So if a transaction has many outputs it can contain many public labels: one for each output.

**Comment by hrobeers** [comment]
@marlengit unless this has been changed in BU, standardness rules allow only one OP_RETURN output per transaction and require it to be smaller than 80bytes.

If this rule still applies in BU nodes, using multiple labels would make your transaction non-standard and very hard to get propagated through the network.

**Comment by ptschip** [comment]
@hrobeers I don't see in the code where there is this restriction that only one per tx...i believe it's only one per output as @marlengit suggests.  I've tested it out and sent multi output, multi public label txns (at least on regtest) from a BU node to a Core v15 node...the Core node accepts the txn and when I mine a block on the Core node, the txn is added to the block...there is no issue that I can see.

The one thing I do notice is that a Core node will not display the public label anywhere... @marlengit is that a limitation of their node or something to do with our public lables?

**Comment by sickpig** [comment]
@ptschip I think that @hrobeers is right, standardness rules allow only one OP_RETURN, I guess that this rule is relaxed while on `regtest`. 

Still we should only have on OP_RETURN per transaction on `mainchain` if we care about our tx to be relayed. 

@ptschip @DesWurstes is the problem still present in BU qt 1.3.0.1?

**Comment by DesWurstes** [comment]
> is the problem still present in BU qt 1.3.0.1?

No, ~~it's fixed~~ it's not. The "Public label" box is completely broken, more importantly. 🤣

Edit: it's not fixed.

**Comment by sickpig** [comment]
@DesWurstes thanks for the heads up. 

Do we have already an issue opened for "Public label" problem?

**Comment by DesWurstes** [comment]
When you fill the public label box and press the "send" button, it asks you for confirmation and wallet password, then it doesn't make a transaction like you never tried to make a transaction.

I guess both problems should be in the same issue.

**Comment by sickpig** [comment]
@DesWurstes thanks for further providing feed back about the bug. Will look into it.

**Comment by ptschip** [comment]
@DesWurstes I don't have any issues with this testing on regtest between two regtest peers.  I've got an encryped wallet , sending to two addresses using public labels on both of them.  No issues that I can see.  I'm using the current dev but I don't think anything has changed from 'release'.  Is this still happening for you?

**Comment by DesWurstes** [comment]
On my mac, after I confirm making a transaction with one OP_RETURN box filled on regtest/testnet/mainnet, the transaction doesn't appear on the transactions list nor gets relayed.

**Comment by ptschip** [comment]
oh, you're on mac..hmmm , maybe it's just related to mac.

I'm on Windows 10/7 and using a BU node sending to an ABC node.  It works fine...with single or multi public labels.  Messages get routed from BU to ABC and  show up right away in the wallet as Pending...then when mined the balance is updated correctly also.

**Comment by ptschip** [comment]
I'm not even sure why it's getting routed to ABC...i thought it wouldn't but looking at the code, ABC and BU nodes are only checking if whichtype = TX_NULL_DATA (you can't have multi TX_NULL_DATA).  So somehow this code isn't getting triggered with the public labels even though it uses op_return.

**Comment by ptschip** [comment]
@sickpig you have a mac? maybe you can try sending txn with multi-public labels?

**Comment by DesWurstes** [comment]
Mine fails on at least one public label.

**Comment by sickpig** [comment]
Will give it a try on my Mac tomorrow my time.

**Comment by ptschip** [comment]
@DesWurstes what version of QT and Boost are you running?

**Comment by sickpig** [comment]
If he's using official binaries he's using Qt 5.6 and boost 1.61

**Comment by ptschip** [comment]
@DesWurstes taking a deeper look at the code, even though public labels use op_return they don't get flagged as TX_NULL_DATA (that is also true for ABC nodes).  In the code, there is a lot more to determining whether an output is TX_NULL_DATA than just checking if it has an OP_RETURN in it.  (The public labels are  OP_RETURN << OP_BIGINTEGER << OP_DATA).  So that's why we can have a different public label for each output and it will still get routed through the network.

**Comment by sickpig** [comment]
@DesWurstes 

sorry for the late reply.

I tried to reproduce the problem in regtest mode using current `dev` (3abaeeb5b0) w/ no luck. 

First test was a simple 2 input / 1 output tx w/ a public label set to some random string and it worked like expected. 

Second test: 2 in / 2 out, set public able to some random strings for both output and again everything went smooth. 

Do you mind trying to reproduce the issue using current `dev` (3abaeeb5b0) ?

**Comment by DesWurstes** [comment]
I can't compile it. On the contrary, I noticed that my problem wasn't that it isn't making public label transactions, but the transactions don't show up in tx history, although it relays them.

**Comment by ptschip** [comment]
which history do you not see them in, the sender or the receiver or both?

fyi, if in the receiver and you sent to two different addressess, they
will show as two different transations, one for each receive address.

**Comment by DesWurstes** [comment]
**Now I completely understand the issue!** :))

It only happens when I send coins to myselt.

**Comment by ptschip** [comment]
using current dev branch it shows up fine for me on win10.  If i send a
tx with one or multiple public labels I see them in both the "recent
transaction" history in QT as well as the transaction list in the
Transactions tab.

@sickpig  can you try it on Mac and see if you are getting the same.

**Comment by DesWurstes** [comment]
Setup: Generate receiving address. Paste it into the "to" field. Fill the public label field below it. Confirm it. So, it just doesn't work for me when I send coins to my address and fill one public label field.

**Comment by ptschip** [comment]
so are you sending this then to yourself?  not to another peer?

**Comment by ptschip** [comment]
ah ok, i was able to recreate the problem by sending to myself...i'll
look at that.

**Comment by sickpig** [comment]
@DesWurstes 

> I can't compile it. 

care to share some details, I will be glad to help you out to solve your compilation problem on osx. 

> It only happens when I send coins to myselt.

great!

now that @ptschip could reproduce the problem on win10 we have better condition to solve the problem. 

thanks again to keep up providing us feedback.

**Comment by ptschip** [comment]
I opened PR 1133 which fixes this issue.
