### ISSUE TITLE
[BUCash v1.1.1.1]: -enable-upnp-default ist not working

### ISSUE THREAD

**Issue by theBergmann** [gandrewstone/bitcoin#777]
Another issue: I tried to start BUCash-v-1.1.1.1 with the flag -enable-upnp-default. While btc1 & bitcoinABC accept the flag, BUCash gives an error. Has this flag been changed?

**Comment by sickpig** [comment]
never used, but looking at the code it should be `-upnp=1` or `upnp=1` is added to the `bitcoin.conf` file.

BitcoinABC, btc1 and core will start even if you try to pass a non valid flag/params. Classic and BU on the other hand will raise an error.

**Comment by theBergmann** [comment]
Ah, thanks, it's working. Good to know the difference!
