### ISSUE TITLE
Transactions tab display issues

### ISSUE THREAD

**Issue by Justaphf** [gandrewstone/bitcoin#778]
This appears to be inconsistencies/bugs in how the "Address or Label" column displays now, related to the changes for the coin-freeze UI.

Old behavior:
The "Address or Label" column showed:
* Sent transactions -> The label associated with the send to address OR the send to address (if no label)
* Received transactions -> The label associated with my receiving address OR my receiving address (if no label)
* Payment to self -> Always displayed as "(n/a)"
* Mined transactions -> show up as mined transaction type and show the label associated with my mining address OR my mining address (if no label)

Current behavior:
The "Address or Label" column now shows:
* Sent transactions -> The label associated with the send to address (if there is one) AND the send to address AND the change address (if there is one)
* Received transactions -> The label associated with my receiving address (if there is one) AND my receiving address AND all other output addresses in the transaction, even if they aren't mine
  * really messy with mining pool payouts
* Payment to self -> The label associated with my receive address (if there is one) AND my receive address AND the change address (if there is one)
* Mined transactions -> now show up as "Received with" transaction type and show the label associated with my mining address (if there is one) AND my mining address AND all other output addresses in the coinbase transaction
  * really messy with P2Pool mining outputs

Other display issues that seem related:
* The tool tips when mousing over a row goes beyond the edge of the screen for long lists of addresses
* The right-click functionality for "Copy Address" now copies the entire contents of the cell, always.  Previously it would only copy the single pertinent address to the transaction (my receiving address, my mining address, the address I sent to)
* The color of the "Address or Label" column is now light grey rather than black unless the first address listed is known in the "Sending Addresses" or "Receiving Addresses" lists with a label
  * Previously would only be grey if the address wasn't in the list, didn't have a label, or was a payment to self.

**Comment by Justaphf** [comment]
Similar reports in this comment: https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/508#issuecomment-322412657

**Comment by sickpig** [comment]
Since we merged @marlengit's #726 we got a bunch of issues, I guess we should have waiting a little bit more. @Justaphf thanks for pointing out all these problems, we are going to fix it.

**Comment by sickpig** [comment]
@Justaphf which version of Qt are you using?

**Comment by Justaphf** [comment]
@sickpig I am using Qt v5.3.2, built from source natively on Windows 10 using MinGW

**Comment by marlengit** [comment]
I've been offline for a few months but I am back now and can help with this. 
Previously the Address or Label column was excluding addresses relevant to the transaction. So when a user did a search filter for one of their relevant addresses nothing would show up. 

In order to search/filter for all addresses then they must be included with the label which is why I output both the private label and the addresses. 

Can you describe what you mean by 'messy'? Is there irrelevant information or could it be formatted better?

**Comment by Justaphf** [comment]
Hi marlengit, thanks for taking a look at this.

Good point on the search functionality.  I never used it in the past for finding transaction addresses/labels so it didn't occur to me.  Since that column previously only ever showed 1 label or 1 address, I normally just sorted by that column if I wanted to find a transaction by address/label quickly.

What I meant by messy is that when I receive payment via a transaction that is paying 10's to 100's of other accounts all of the output addresses are now listed in this column, not just mine.  As an example, I have an old P2Pool block reward where the coinbase was sent to 137 addresses.  Maybe there's a reason to search all the output addresses in this case, but from my perspective it's now 136 spots of noise obscuring the 1 address I actually care about.  It also prevents me from using the `Copy Address` right-click option to copy just my address, I now get every address and label so it is no longer useful for quick copy and paste of my address from the transactions tab.

On the other hand, for a sent transaction, I would certainly want to be able to search each and every one of the output addresses/labels I sent money to, so in this case having them all listed/searchable is nice.

Either way, the long list of addresses/labels causes some UI issues:
1. Prevents the user from being able to fully see the contents of the column no matter how wide the application is resized due to the length of the cell contents.
  a. This might be mitigated some if the row heights were user adjustable and the cell supported newlines, however multi-line table rows can have their own display issues.
2. Causes the mouse-over tooltip to cross the entire screen and run off the right side.
  a. This could potentially be made to look nicer by making the text displayed in the tool-tip tabular with newlines and tabs for formatting, though depending on the number of outputs this could end up covering the entire screen, and with variable length labels making a well aligned table layout could be problematic.

I also noticed one more thing while looking at it tonight.  For addresses which have private labels, the private label still shows up as the very first thing, but the address which follows it isn't the one associated with the label unless it happened to be the first output in the transaction.  This could be confusing to the user.  It might make more sense to reorder the privately labeled address to always be the first one so that it lines up with the private label.  I don't know that there is a need to keep all addresses in the same order they appear in the raw transaction when displayed in this table.
NOTE: I don't have any transactions where multiple addresses have private labels, so I'm not sure how this is currently handled, but I would think we'd want the private, public, and address all to be grouped.

**Comment by marlengit** [comment]
> Mined transactions -> now show up as "Received with" transaction type and show the label associated with my mining address (if there is one) AND my mining address AND all other output addresses in the coinbase transaction    really messy with P2Pool mining outputs

This one is definately not by design. The first three are working as designed. I will fix or revert to the old behaviour for mined transaction types.

**Comment by marlengit** [comment]
Thanks for you feedback I will work on the improvements you suggested.

**Comment by Justaphf** [comment]
@marlengit The changes look good on the Overview tab and the Transactions tab for sent/received/payment to self, however, when I try to view Mined transactions the application crashes.  First happened scrolling the list of transactions, then also reproduced filtering to only show mined transactions. 
Nothing useful in the log file or the Windows system events logs.

Test System:
* Windows 10 64-bit
* bitcoin-qt.exe 64-bit
* Clean rebuild from source (dev branch: 8f23bb2) using MinGW to compile natively on Windows
* Qt version 5.3.2

It's possible this is related to the fact that I built with MinGW or my version of Qt (5.3.2).  When I get some free time I'll try running on a Linux box and see if it's reproducible there as well.

**Comment by marlengit** [comment]
@Justaphf thanks, I will take a closer look at how the mined transactions are being handled. It would help if I could get some examples of mined transactions in a wallet so I can do local testing. Do you have a testnet wallet with "Mined" transactions?

**Comment by Justaphf** [comment]
@marlengit Sorry it's taken so long to get back to you.  I do have a wallet from the Nolimit Testnet with mined transactions I can give you.  It's from a while ago and I'm pretty sure all of the mined blocks are from a dead fork, but I deleted all blocks and started the latest `dev` client to begin syncing from scratch and the issue is reproducible for this wallet.

I've attached the config file I used to connect to nolnet and a copy of the wallet (non-encrypted).
[nol.zip](https://github.com/BitcoinUnlimited/BitcoinUnlimited/files/1456525/nol.zip)

To reproduce, once a few hundred blocks have downloaded go to the Transactions tab and start scrolling down (will crash when you get to the first mined transaction).

Test system was Windows 10, and the "install" location for `bitcoin-qt` was `C:\NolTestNet\`
Start command (I just had this in a batch file):
`start /B "" "C:\NolTestNet\bitcoin-qt.exe" -conf=C:\NolTestNet\bitcoin.conf -datadir=C:\NolTestNet`

**Comment by Justaphf** [comment]
One more thing about that wallet, once the chain fully synced up, it looks like the most recent set of transactions are of type "mined" so the application will crash immediately when you switch to the transactions tab.

**Comment by sickpig** [comment]
@Justaphf have the additional issues reported here(*) been fixed if using the latest version of `dev`? 

(*) crashing related to the display of "mined" type transactions

**Comment by Justaphf** [comment]
@sickpig I'll try and get a build from latest dev this weekend and re-verify.  I didn't hear anything back from @marlengit  after uploading the example wallet file for nolnet or see any new related commits, and I've been pretty snowed under with my day job since September so haven't really looked into it.  It's possible that it was corrected by one of the address label fixes @ptschip has been making recently.

**Comment by Justaphf** [comment]
@sickpig It looks like the latest `dev` branch, as of fac440c, fixed this crash.

I am marking this issue as closed.
