### ISSUE TITLE
Bitnodes seeding not working

### ISSUE THREAD

**Issue by patrikr** [gandrewstone/bitcoin#834]
`Bitnodes Exception: Bitnodes returned HTTP status 301`

Probably related to their rebranding from 21.co to earn.com?

**Comment by sickpig** [comment]
ouch indeed. will fix in the next release. 
in the mean time please disable bitnodes seeding and use the hardcoded seeders, thanks.

**Comment by sickpig** [comment]
#835 fixed the issue. closing
