### ISSUE TITLE
Weird transactions list in BUcash

### ISSUE THREAD

**Issue by patrikr** [gandrewstone/bitcoin#838]
A transaction that has three outputs is displayed like this in BU 1.0.3:

- Sent to:  Abc  -1.00000000
- Sent to:  Def  -2.00000000
- Sent to:  Xyz  -3.00000000

But in BUcash 1.1.2, the same transaction is displayed like this:

- Sent to: Xyz 1sdkgvewiuvbiwevbjkwebv 1sedugheosghewsgbvgwke 1sdkgbesodbvihsoebviues  -1.00000000
- Sent to: Xyz 1sdkgvewiuvbiwevbjkwebv 1sedugheosghewsgbvgwke 1sdkgbesodbvihsoebviues  -2.00000000
- Sent to: Xyz 1sdkgvewiuvbiwevbjkwebv 1sedugheosghewsgbvgwke 1sdkgbesodbvihsoebviues  -3.00000000

I.e. incorrect label for two lines, and then a listing of all the receiving addresses. If I open up the transaction details window, I can see the correct sums sent to each address.

**Comment by sickpig** [comment]
@patrikr thanks for reporting! Looking into it.

**Comment by theBergmann** [comment]
I came here to report the same issue. Happy to see transactions on the screen, but the order is weird. I wondered if it had something to do with the public label, as the labelled is on top.
