### ISSUE TITLE
make check fails for BU 0.12.0

### ISSUE THREAD

**Issue by atisharma** [gandrewstone/bitcoin#84]
complied with:

`$ ./configure --without-gui --enable-upnp-default --disable-wallet --prefix=/usr/local`

`make check` gives

```
==================================================
   Bitcoin Unlimited 0.12.0: src/test-suite.log
==================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0


.. contents:: :depth: 2

FAIL: test/test_bitcoin
=======================

Running 180 test cases...
test/DoS_tests.cpp(171): error in "DoS_mapOrphans": check AddOrphanTx(tx, i) failed

*** 1 failure detected in test suite "Bitcoin Test Suite"
```

`$ uname -a`
`Linux vostok 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux`

**Comment by Justaphf** [comment]
Hi atisharma, thanks for reporting this issue.

I do not know the exact cause of this issue, but I have been able to reproduce the issue with the 0.12.1b client source code (this is 1 minor release and 1 hotfix ahead of your indicated test version of 0.12.0).  The error seems to be intermittent related to the randomized nature of the test case for DoS_mapOrphans.  In my tests about 50% failed and 50% passed this particular regression test with the 0.12.1b client (out of 10 manually run test cases).

The team is investigating this issue and will let you know once we have more information and/or have a fix or explanation as to the cause.  If you have any additional information please let us know as this will be helpful in debugging the problem.

**Comment by sickpig** [comment]
@atisharma 

have you tried to reproduce the issue on the current 0.12.1bu branch?

**Comment by atisharma** [comment]
@sickpig I have been unable to reproduce with 0.12.1bu having tried `make check` 5 times.

**Comment by atisharma** [comment]
I shall close the issue based on your band aid fix above. Thanks.

**Comment by sickpig** [comment]
@atisharma great! thanks for testing it.
