### ISSUE TITLE
[BUCash v1.1.2.0] Extra whitespace in date formatting

### ISSUE THREAD

**Issue by awpcrypto** [gandrewstone/bitcoin#846]
There is extra whitespace between the Month and Date in the **Debug window** (**Information Tab**).

I have attached an image. The yellow highlight points to where the extra whitespace is.

EDIT: I believe that a newer and updated format was added in later versions of the software. I am not sure as to which version that would be.

![image](https://user-images.githubusercontent.com/33704459/33246227-0924acc0-d2e0-11e7-8411-add12cde46aa.png)

**Comment by ptschip** [comment]
fixed in #901

**Comment by sickpig** [comment]
fixed by #901, closing. thanks @ptschip !
