### ISSUE TITLE
Copy Address becomes Copy Private Label + Address

### ISSUE THREAD

**Issue by theBergmann** [gandrewstone/bitcoin#855]
There is a minor bug when going on the transaction page, clicking the right mouse button and selecting "copy address": It copies private label + adress, "private label 1bitcoincash..."

When you published a public label, it copies "private label <public label> 1bitcoincash ..."

Not that this is much of a worry ...

**Comment by sickpig** [comment]
copying here a work around stated by @ptschip in the BU slack:
"....you can go to your list of addresses and edit them there rather than try from the transaction list view."
just to use in the meantime.

**Comment by ptschip** [comment]
fixed in #898

**Comment by sickpig** [comment]
closing, as @ptschip said #898 fixed it
