### ISSUE TITLE
Clicking "Edit Label" under the transactions page prepends the label to the address field instead of the label field

### ISSUE THREAD

**Issue by WestonReed** [gandrewstone/bitcoin#872]
![bulabelbug](https://user-images.githubusercontent.com/11198372/34370691-cf4d5a24-ea8b-11e7-8bbc-7aa73d7a59fa.png)

**Comment by sickpig** [comment]
thanks for the report

**Comment by ptschip** [comment]
fixed in #898

**Comment by sickpig** [comment]
closing, as @ptschip said #898 fixed it
