### ISSUE TITLE
GUI won't compile. Compile error with QT

### ISSUE THREAD

**Issue by nettijoe96** [gandrewstone/bitcoin#876]
Hi, I cloned the repo and tried to make the Bitcoin cash client. bitcoind and bitcoin-cli compilied but the gui did not. I got this error: 

`In file included from qt/receivefreezedialog.cpp:6:0:
./qt/forms/ui_receivefreezedialog.h: In member function ‘void Ui_ReceiveFreezeDialog::setupUi(QDialog*)’:
./qt/forms/ui_receivefreezedialog.h:140:45: error: ‘ImhDate’ is not a member of ‘Qt’
         freezeDateTime->setInputMethodHints(Qt::ImhDate|Qt::ImhTime);
                                             ^
./qt/forms/ui_receivefreezedialog.h:140:57: error: ‘ImhTime’ is not a member of ‘Qt’
         freezeDateTime->setInputMethodHints(Qt::ImhDate|Qt::ImhTime);
            `

**Comment by nettijoe96** [comment]
Got it working with qt5. For bitcoin cash gui, you need qt5 and qt4 doesn't work.

**Comment by sickpig** [comment]
thanks for the report.

**Comment by soeren-b-c** [comment]
One could argue that support for qt4 is not that important?

If that is the case should the documentation be updated to reflect this change? Or should we wait and see for this to get fixed?

**Comment by sickpig** [comment]
qt4 support has been deprecated, see #1011. 
closing.
