### ISSUE TITLE
tab/space mixed

### ISSUE THREAD

**Issue by chengchen09** [gandrewstone/bitcoin#90]
There are some new codes using tab as indentation instead of space, and make code looks confusing.
for example:

```
            if (depth < excessiveAcceptDepth)
          {
        fRecentExcessive |= ((pindexTest->nStatus & BLOCK_EXCESSIVE) != 0);  // Unlimited: deny this candidate chain if there's a recent excessive block
          }
            else
          {
        fOldExcessive |= ((pindexTest->nStatus & BLOCK_EXCESSIVE) != 0);  // Unlimited: unless there is an even older excessive block
          }
```

**Comment by gandrewstone** [comment]
yes, I want to move to spaces only.  Unfortunately, we cannot simply reformat the entire set of files using an automated tool because its important from a rebasing perspective to not make cosmetic changes to the Core code.  So we will need to fix these ONLY in the BU changes as they arise.
