### ISSUE TITLE
gigaperf: makeGroup(..) function in coinselection.cpp broken for gigaperf branch

### ISSUE THREAD

**Issue by awemany** [gandrewstone/bitcoin#912]
This is likely for @gandrewstone :

I tried doing a 'sendtoaddress' on my weakblocks stuff on top of my gigaperf branch and got a segfault. I am quite sure that the segfault isn't related to my stuff and after consulting stackoverflow regarding the handling of null-references, I am sure that there's an error in here (in coinselection.cpp, commit aa9510b437 (which curiously is from *2016* but doesn't appear in any of the BU branches?!):
```
TxoGroup makeGroup(SpendableTxos::iterator i, const TxoGroup& prev = *(TxoGroup*)NULL)
{
  TxoGroup ret;
  if (&prev) ret = prev;
```
With the `sendtoadress` RPC call, I get a segfault on the `if (&prev) ...` line. Stackoverflow regarding null references (which I never encountered or thought much about, seemingly for good reason):

https://stackoverflow.com/a/4364586

**Comment by gandrewstone** [comment]
fixed, closing
