### ISSUE TITLE
Discoloration of icon

### ISSUE THREAD

**Issue by Greg-Griffith** [gandrewstone/bitcoin#919]
There have been reports that the icon shows up as gray in the task bar, gray on the exe, and the correct green in the tray. 

for me personally it is gray on the taskbar although the top left of the exe and the tray are both green (win10 64bit)

edit: my exe icon on my desktop is gray as well

**Comment by Justaphf** [comment]
I am seeing this on Win10 x64 with latest dev branch.  For the file icon, it is grey for all sizes.

![exe icon](https://user-images.githubusercontent.com/6402604/35025610-823e05a0-fb14-11e7-87c6-88f7ef06b13d.PNG)
![task bar](https://user-images.githubusercontent.com/6402604/35025611-8248f37a-fb14-11e7-905d-bbd7b6b92a60.PNG)

**Comment by Greg-Griffith** [comment]
i have a graphic designer friend who is fixing it for me

**Comment by Greg-Griffith** [comment]
addressed and fixed in #936

**Comment by Greg-Griffith** [comment]
this was fixed in #940
