### ISSUE TITLE
Unable to sync new full node. Bad seed peers?

### ISSUE THREAD

**Issue by lmanners** [gandrewstone/bitcoin#941]
Hi,

When I try to run a full node (compiled from release branch) I get stuck at around 300k blocks, and can't seem to find any peers who have the rest of the blockchain.

I tried deleting peers.dat and restarting, as well as a fresh uninstall / install, but I ended up in the same state.

It seems as if I am getting grouped with a set of orphaned peers, where no one has the full blockchain.

Here is my output from getpeerinfo:
https://hastebin.com/ecahibajop.json

And getblockchaininfo:
https://hastebin.com/jeliqipuyo.json

I'm new to running a full node, apologies in advance if I'm doing something wrong.

**Comment by ptschip** [comment]
Can you do a couple of things:

1) stop the node and delete the peers.dat again
2) when you startup (either in bitcoin.conf or from the command line)
can you set "maxoutconnections=30"  and also "bitnodes=0"

Let us know how it's going.  also remember to set your -dbcache
correctly when syncing to as much available memory as you can spare...if
you have 3GB availalble
then set your "dbcache=3000"

**Comment by lmanners** [comment]
Thank you, your changes worked!

Because I followed all your instructions in one go, I can't tell which one(s) got me unstuck.

Relatedly, I don't know if I did something wrong, or if there's an underlying issue where the default settings sometimes can't sync.

Would it help if I looked into it / tried to repro the problem?

**Comment by ptschip** [comment]
if the problem can be reliably reproduce that would help us...i suspect
though you just had a bad set of peers.

**Comment by ptschip** [comment]
we're about to put out a bugfix release in the next day or two..if you
do any testing you might want to do it on the new release...

**Comment by lmanners** [comment]
I tried to sync again from scratch doing a fresh build with the latest release. Again, syncing became very slow around block 300,000 (I seem to be stuck).

Here is what I have from getpeerinfo:
https://hastebin.com/upobihenom.json

I deleted peers.dat once and restarted my server, but it didn't seem to help.

So far I've been able to reproduce this reliably whenever I sync from scratch with a default config.

**Comment by sickpig** [comment]
@lmanners 

@ptschip have done a lot of great work to improve IBD perf. If you are fluent compiling the binaries from source you could give PR #970 a try and see if it works better and fix the problem for you. 

if you want I could built a gitian set of binaries from your platform. Just let me know.

**Comment by lmanners** [comment]
I'll try syncing again with PR #970 applied and report back.

**Comment by lmanners** [comment]
With PR #970 applied I was able to successfully sync from scratch on my first attempt.

A couple things I observed during the sync:
103GB of the block chain was served to my node by a single peer (!)
The version I patched contains a printf statement which spammed the console a bit.

**Comment by ptschip** [comment]
thanks, you must have grabbed the patch before I finished updating
it...the printf statements are not there anymore. 

btw, how long did it take you to sync?

what size of dbcache did you use?

**Comment by lmanners** [comment]
It took about 10 hours to sync, with dbcache=3000.

**Comment by ptschip** [comment]
that's not bad... depends on other factors also .. i takes me 3 hrs but
I have great bandwidth and a decent cpu and SSD.

btw, thanks for reporting that issue with the peer taking on more than
it's share of bandwidth...while we do prefer to download from faster
peers , that was way over what it should be doing.  I found a good
solution and tested it out and it works...and pushed up the commits. 
The problem was that the very first peer to connect will always have
preference in sending out messages...so you end up sending from the
first peer and then you get back blocks and then send messages again
from the first peer....and round and round you go...so all I'm doing
here is rotating the position in the list for the first peer, every
minute during the sync period. 

Problem solved...thanks again !
