### ISSUE TITLE
Test suite fails on fresh build on debian, no idea as to why

### ISSUE THREAD

**Issue by deadalnix** [gandrewstone/bitcoin#96]
Test suite log :
# 
#    Bitcoin Unlimited 0.12.1: src/test-suite.log
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2
# FAIL: test/test_bitcoin

Running 182 test cases...
../../src/test/DoS_tests.cpp(172): error: in "DoS_tests/DoS_mapOrphans": check AddOrphanTx(tx, i) has failed
terminate called without an active exception
unknown location(0): fatal error: in "reverselock_tests/reverselock_errors": signal: SIGABRT (application abort requested)
../../src/test/reverselock_tests.cpp(51): last checkpoint
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_rawparams": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(54): last checkpoint: "rpc_rawparams" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_rawsign": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(96): last checkpoint: "rpc_rawsign" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_createraw_op_return": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(115): last checkpoint: "rpc_createraw_op_return" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_format_monetary_values": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(133): last checkpoint: "rpc_format_monetary_values" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_parse_monetary_values": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(175): last checkpoint: "rpc_parse_monetary_values" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/json_parse_errors": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(208): last checkpoint: "json_parse_errors" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "rpc_tests/rpc_ban": signal: SIGABRT (application abort requested)
../../src/test/rpc_tests.cpp(229): last checkpoint: "rpc_ban" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "sanity_tests/basic_sanity": signal: SIGABRT (application abort requested)
../../src/test/sanity_tests.cpp(14): last checkpoint: "basic_sanity" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/sign": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(55): last checkpoint: "sign" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/norecurse": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(129): last checkpoint: "norecurse" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/set": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(156): last checkpoint: "set" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/is": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(213): last checkpoint: "is" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/switchover": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(244): last checkpoint: "switchover" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_P2SH_tests/AreInputsStandard": signal: SIGABRT (application abort requested)
../../src/test/script_P2SH_tests.cpp(264): last checkpoint: "AreInputsStandard" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_build": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(320): last checkpoint: "script_build" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_valid": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(631): last checkpoint: "script_valid" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_invalid": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(660): last checkpoint: "script_invalid" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_PushData": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(685): last checkpoint: "script_PushData" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_CHECKMULTISIG12": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(747): last checkpoint: "script_CHECKMULTISIG12" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_CHECKMULTISIG23": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(777): last checkpoint: "script_CHECKMULTISIG23" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_combineSigs": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(846): last checkpoint: "script_combineSigs" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_standard_push": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(955): last checkpoint: "script_standard_push" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_IsPushOnly_on_invalid_scripts": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(976): last checkpoint: "script_IsPushOnly_on_invalid_scripts" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "script_tests/script_GetScriptAsm": signal: SIGABRT (application abort requested)
../../src/test/script_tests.cpp(987): last checkpoint: "script_GetScriptAsm" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "scriptnum_tests/creation": signal: SIGABRT (application abort requested)
../../src/test/scriptnum_tests.cpp(168): last checkpoint: "creation" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "scriptnum_tests/operators": signal: SIGABRT (application abort requested)
../../src/test/scriptnum_tests.cpp(181): last checkpoint: "operators" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/sizes": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(19): last checkpoint: "sizes" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/floats_conversion": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(50): last checkpoint: "floats_conversion" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/doubles_conversion": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(69): last checkpoint: "doubles_conversion" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/floats": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(98): last checkpoint: "floats" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/doubles": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(115): last checkpoint: "doubles" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/varints": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(132): last checkpoint: "varints" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/compactsize": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(164): last checkpoint: "compactsize" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/noncanonical": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(195): last checkpoint: "noncanonical" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "serialize_tests/insert_delete": signal: SIGABRT (application abort requested)
../../src/test/serialize_tests.cpp(232): last checkpoint: "insert_delete" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "sighash_tests/sighash_test": signal: SIGABRT (application abort requested)
../../src/test/sighash_tests.cpp(124): last checkpoint: "sighash_test" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "sighash_tests/sighash_from_data": signal: SIGABRT (application abort requested)
../../src/test/sighash_tests.cpp(171): last checkpoint: "sighash_from_data" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "sigopcount_tests/GetSigOpCount": signal: SIGABRT (application abort requested)
../../src/test/sigopcount_tests.cpp(30): last checkpoint: "GetSigOpCount" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "skiplist_tests/skiplist_test": signal: SIGABRT (application abort requested)
../../src/test/skiplist_tests.cpp(19): last checkpoint: "skiplist_test" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "skiplist_tests/getlocator_test": signal: SIGABRT (application abort requested)
../../src/test/skiplist_tests.cpp(48): last checkpoint: "getlocator_test" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "streams_tests/streams_serializedata_xor": signal: SIGABRT (application abort requested)
../../src/test/streams_tests.cpp(19): last checkpoint: "streams_serializedata_xor" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "timedata_tests/util_MedianFilter": signal: SIGABRT (application abort requested)
../../src/test/timedata_tests.cpp(15): last checkpoint: "util_MedianFilter" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "transaction_tests/tx_valid": signal: SIGABRT (application abort requested)
../../src/test/transaction_tests.cpp(88): last checkpoint: "tx_valid" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "transaction_tests/tx_invalid": signal: SIGABRT (application abort requested)
../../src/test/transaction_tests.cpp(163): last checkpoint: "tx_invalid" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "transaction_tests/basic_transaction_tests": signal: SIGABRT (application abort requested)
../../src/test/transaction_tests.cpp(237): last checkpoint: "basic_transaction_tests" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "transaction_tests/test_Get": signal: SIGABRT (application abort requested)
../../src/test/transaction_tests.cpp(291): last checkpoint: "test_Get" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "transaction_tests/test_IsStandard": signal: SIGABRT (application abort requested)
../../src/test/transaction_tests.cpp(317): last checkpoint: "test_IsStandard" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "tx_validationcache_tests/tx_mempool_block_doublespend": signal: SIGABRT (application abort requested)
../../src/test/txvalidationcache_tests.cpp(30): last checkpoint: "tx_mempool_block_doublespend" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "versionbits_tests/versionbits_test": signal: SIGABRT (application abort requested)
../../src/test/versionbits_tests.cpp(137): last checkpoint: "versionbits_test" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "versionbits_tests/versionbits_computeblockversion": signal: SIGABRT (application abort requested)
../../src/test/versionbits_tests.cpp(213): last checkpoint: "versionbits_computeblockversion" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "uint256_tests/basics": signal: SIGABRT (application abort requested)
../../src/test/uint256_tests.cpp(76): last checkpoint: "basics" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "uint256_tests/comparison": signal: SIGABRT (application abort requested)
../../src/test/uint256_tests.cpp(128): last checkpoint: "comparison" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "uint256_tests/methods": signal: SIGABRT (application abort requested)
../../src/test/uint256_tests.cpp(160): last checkpoint: "methods" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "uint256_tests/conversion": signal: SIGABRT (application abort requested)
../../src/test/uint256_tests.cpp(254): last checkpoint: "conversion" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_constructor": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(18): last checkpoint: "univalue_constructor" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_typecheck": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(66): last checkpoint: "univalue_typecheck" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_set": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(108): last checkpoint: "univalue_set" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_array": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(167): last checkpoint: "univalue_array" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_object": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(205): last checkpoint: "univalue_object" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "univalue_tests/univalue_readwrite": signal: SIGABRT (application abort requested)
../../src/test/univalue_tests.cpp(291): last checkpoint: "univalue_readwrite" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_criticalsection": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(25): last checkpoint: "util_criticalsection" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_ParseHex": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(52): last checkpoint: "util_ParseHex" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_HexStr": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(69): last checkpoint: "util_HexStr" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_DateTimeStrFormat": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(91): last checkpoint: "util_DateTimeStrFormat" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_ParseParameters": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(100): last checkpoint: "util_ParseParameters" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_GetArg": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(124): last checkpoint: "util_GetArg" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_FormatMoney": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(148): last checkpoint: "util_FormatMoney" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_ParseMoney": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(173): last checkpoint: "util_ParseMoney" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_IsHex": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(221): last checkpoint: "util_IsHex" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_seed_insecure_rand": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(236): last checkpoint: "util_seed_insecure_rand" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/util_TimingResistantEqual": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(266): last checkpoint: "util_TimingResistantEqual" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/strprintf_numbers": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(281): last checkpoint: "strprintf_numbers" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/gettime": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(307): last checkpoint: "gettime" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_ParseInt32": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(312): last checkpoint: "test_ParseInt32" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_ParseInt64": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(341): last checkpoint: "test_ParseInt64" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_ParseDouble": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(371): last checkpoint: "test_ParseDouble" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_FormatParagraph": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(399): last checkpoint: "test_FormatParagraph" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion`secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_FormatSubVersion": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(411): last checkpoint: "test_FormatSubVersion" fixture entry.
test_bitcoin: ../../src/key.cpp:306: void ECC_Start(): Assertion `secp256k1_context_sign == NULL' failed.
unknown location(0): fatal error: in "util_tests/test_ParseFixedPoint": signal: SIGABRT (application abort requested)
../../src/test/util_tests.cpp(423): last checkpoint: "test_ParseFixedPoint" fixture entry.

**\* 81 failures are detected in the test module "Bitcoin Test Suite"
FAIL test/test_bitcoin (exit status: 201)

**Comment by sickpig** [comment]
@deadalnix 

PR #95 should temporarily fix the problem. Is a one liner patch. Could please try to give it a try?

**Comment by deadalnix** [comment]
Good, it work ! Tanks !
