### ISSUE TITLE
MAX_OUTBOUND_CONNECTIONS should be per address family

### ISSUE THREAD

**Issue by nshopik** [gandrewstone/bitcoin#97]
MAX_OUTBOUND_CONNECTIONS is currently limited to 8 connections and doesn't separate IPv4/IPv6 connections. So there is cases when you could connect to 8 IPv4 nodes even though you have IPv6 available.

As IPv4 and IPv6 completely separate networks and usually with different routing, BU should treat them separately and make 8 IPv4 and 8 IPv6 connections. Otherwise current implementation make IPv6 protocol less interconnected for nodes.

**Comment by sickpig** [comment]
@nshopik in current BU code there's no more instances of MAX_OUTBOUND_CONNECTIONS. We have replaced it with DEFAULT_MAX_OUTBOUND_CONNECTIONS (currently equal to 8) that is used to determine the number of default outbound connections. Such settings could be changed at startup using `maxoutconnections` parameter.

I know that @Justaphf have worked on it after the initial commit to fix some bugs on the code related to this feature (some of them was there before).

I'll have a look at the separation of IPv6 and IPv4 connections.

**Comment by nshopik** [comment]
> We have replaced it with DEFAULT_MAX_OUTBOUND_CONNECTIONS (currently equal to 8) that is used to determine the number of default outbound connections. Such settings could be changed at startup using maxoutconnections parameter.

Yeah I completely forgot about that, especially part where you could set maxoutconnections w/o changing code!

**Comment by sickpig** [comment]
WRT separation of IPv{4,6} from reading the code (see: AcceptConnection in net.cpp line 1103) it seems tha BU currently does not make any distinction between the type of address, be it IPv\* or onion, so all the limits set using aforementioned parameters are enforced globally. There's no way to currently set and enforce a limit per address family.

That said I have no strong opinion about developing code to add this functionality a part form the fact that there are a lot of things with higher prio to be done.

**Comment by ptschip** [comment]
Glad you reported this and we can have a discussion about it but I don't
think we really need to worry about ipv4 or 6 IMO...if someone wants to
connect to either they can through addnode.  All we're doing with the 8
outbounds is getting someone up and running and if they allow inbounds
then there is no problem, and they can up their outbound connection also
if they want to.

**Comment by nshopik** [comment]
@ptschip  I consider `addnode` more useful when you know it will always online, otherwise you have to keep track if its still alive.

Raising `maxoutconnections` probably isn't really good workaround too, as you still fill your outbound connections mostly with IPv4 if not all of them. Currently only solution I see is just running IPv6 only node with `onlynet=ipv6`

> All we're doing with the 8 outbounds is getting someone up and running and if they allow inbounds
> then there is no problem

Well you should consider that other nodes running same `outbound` code so you get less IPv6 connections to your node, and mostly it will be SPV clients. At least this is what I'm seeing.

Why is this matters? quality of IPv6 and IPv4 connection can be varied and if you get connected with 7/1 IPv4/IPv6 suddenly you can only receive txes only from one node if IPv4 connection is getting wrecked because of routing issues.

Though I agree this lowish-priority issue and if its require lots of rework probably somebody else need come-up with pull request

**Comment by ptschip** [comment]
addnode in BU will reconnect when the node comes back up

**Comment by sickpig** [comment]
@gandrewstone this issue should be closed

**Comment by sickpig** [comment]
Closing per https://github.com/BitcoinUnlimited/BitcoinUnlimited/issues/97#issuecomment-248597233 comment
