### ISSUE TITLE
PPA lists bucash as BCC

### ISSUE THREAD

**Issue by WestonReed** [gandrewstone/bitcoin#971]
weston@Weston-Server:/# sudo add-apt-repository ppa:bitcoin-unlimited/bucash
 Bitcoin Unlimited BCC (Bitcoin Cash) edition
 More info: https://launchpad.net/~bitcoin-unlimited/+archive/ubuntu/bucash
Press [ENTER] to continue or ctrl-c to cancel adding it

**Comment by sickpig** [comment]
you are right indeed. going to change the ticker to BCH

**Comment by sickpig** [comment]
done. closing
